#include "imgui_app_icon.h"

#include "flakes_icon_embedded.h" // kFlakesIconPNG — generated by WhiteoutFlakesEmbedded.

#include <whiteout/textures/png/parser.h>

#include <algorithm>
#include <cmath>
#include <cstring>
#include <optional>
#include <span>
#include <utility>
#include <vector>

namespace whiteout::flakes::ui {

namespace {

namespace tx = whiteout::textures;

ImFontAtlasRectId s_rect = ImFontAtlasRectId_Invalid;

/// Box-filter a square RGBA8 image down to @p size a side.
///
/// Averaged in premultiplied alpha, then unpremultiplied: straight-alpha
/// averaging drags the colour of fully transparent pixels into the edge of
/// every arm, and on this icon those pixels are black.
void Resample(const u8* src, i32 srcSize, u8* dst, i32 size) {
    const f32 step = static_cast<f32>(srcSize) / static_cast<f32>(size);
    for (i32 y = 0; y < size; ++y) {
        const i32 y0 = std::clamp(static_cast<i32>(std::floor(static_cast<f32>(y) * step)), 0, srcSize - 1);
        const i32 y1 = std::clamp(static_cast<i32>(std::ceil(static_cast<f32>(y + 1) * step)), y0 + 1, srcSize);
        for (i32 x = 0; x < size; ++x) {
            const i32 x0 = std::clamp(static_cast<i32>(std::floor(static_cast<f32>(x) * step)), 0, srcSize - 1);
            const i32 x1 =
                std::clamp(static_cast<i32>(std::ceil(static_cast<f32>(x + 1) * step)), x0 + 1, srcSize);

            f32 r = 0.0f, g = 0.0f, b = 0.0f, a = 0.0f;
            for (i32 sy = y0; sy < y1; ++sy) {
                for (i32 sx = x0; sx < x1; ++sx) {
                    const u8* p =
                        src + (static_cast<usize>(sy) * static_cast<usize>(srcSize) + static_cast<usize>(sx)) * 4u;
                    const f32 pa = static_cast<f32>(p[3]) / 255.0f;
                    r += static_cast<f32>(p[0]) * pa;
                    g += static_cast<f32>(p[1]) * pa;
                    b += static_cast<f32>(p[2]) * pa;
                    a += pa;
                }
            }
            const f32 n = static_cast<f32>((y1 - y0) * (x1 - x0));
            u8* d = dst + (static_cast<usize>(y) * static_cast<usize>(size) + static_cast<usize>(x)) * 4u;
            const auto quantise = [](f32 v) { return static_cast<u8>(std::lround(std::clamp(v, 0.0f, 255.0f))); };
            d[0] = a > 0.0f ? quantise(r / a) : 0u;
            d[1] = a > 0.0f ? quantise(g / a) : 0u;
            d[2] = a > 0.0f ? quantise(b / a) : 0u;
            d[3] = quantise(255.0f * a / n);
        }
    }
}

} // namespace

void BakeAppIcon(f32 dpiScale) {
    s_rect = ImFontAtlasRectId_Invalid;
    if (dpiScale <= 0.0f)
        dpiScale = 1.0f;

    tx::png::Parser parser;
    std::optional<tx::Texture> decoded = parser.parse(std::span<const u8>(kFlakesIconPNG, sizeof(kFlakesIconPNG)));
    if (!decoded)
        return;
    tx::Texture icon = std::move(*decoded);
    if (icon.format() != tx::PixelFormat::RGBA8)
        icon = icon.copyAsFormat(tx::PixelFormat::RGBA8);
    const i32 srcSize = static_cast<i32>(std::min(icon.width(), icon.height()));
    if (srcSize <= 0 || icon.data().size() < static_cast<usize>(srcSize) * static_cast<usize>(srcSize) * 4u)
        return;

    // Sized for the tile it is drawn on — roughly RibbonMetrics().tileH minus a
    // label — with enough margin that the sampler is minifying rather than
    // magnifying, and never larger than the source.
    const i32 size = std::clamp(static_cast<i32>(std::lround(44.0f * dpiScale)), 16, srcSize);

    // The atlas has to exist before a rectangle can be written into it, and
    // asking for its pixels is what builds it. Packing after the build means
    // nothing repacks underneath the pixels written below.
    ImFontAtlas* atlas = ImGui::GetIO().Fonts;
    u8* pixels = nullptr;
    i32 atlasW = 0;
    i32 atlasH = 0;
    atlas->GetTexDataAsRGBA32(&pixels, &atlasW, &atlasH);
    if (!pixels || atlas->TexData == nullptr || atlas->TexData->BytesPerPixel != 4)
        return;

    ImFontAtlasRect rect{};
    const ImFontAtlasRectId id = atlas->AddCustomRect(size, size, &rect);
    if (id == ImFontAtlasRectId_Invalid)
        return;

    std::vector<u8> scaled(static_cast<usize>(size) * static_cast<usize>(size) * 4u);
    Resample(icon.data().data(), srcSize, scaled.data(), size);

    ImTextureData* tex = atlas->TexData;
    for (i32 y = 0; y < size; ++y) {
        std::memcpy(tex->GetPixelsAt(rect.x, rect.y + y),
                    scaled.data() + static_cast<usize>(y) * static_cast<usize>(size) * 4u,
                    static_cast<usize>(size) * 4u);
    }
    // Font glyphs are white plus alpha; this is the one thing in the atlas that
    // is not, and a backend may compress the texture on that promise.
    tex->UseColors = true;
    s_rect = id;
}

bool AppIconUV(ImVec2* uv0, ImVec2* uv1) {
    if (s_rect == ImFontAtlasRectId_Invalid)
        return false;
    ImFontAtlasRect rect{};
    if (!ImGui::GetIO().Fonts->GetCustomRect(s_rect, &rect))
        return false;
    if (uv0)
        *uv0 = rect.uv0;
    if (uv1)
        *uv1 = rect.uv1;
    return true;
}

} // namespace whiteout::flakes::ui
