// AUTO-GENERATED by cornflakes/cmake/gen_field_defs.py.
// Source: hbo_field_defs.json. Do not edit by hand; regenerate via the build.

#include <cornflakes/asset/field_defs.hpp>

#include <algorithm>
#include <array>

namespace whiteout::cornflakes {
namespace {

// CAnimationClip (3 fields)
constexpr std::array<FieldDef, 3> kFields_CAnimationClip{{
    FieldDef{"EntityStreams", "link[]"},
    FieldDef{"LengthInSeconds", "float"},
    FieldDef{"PlaybackSpeed", "float"},
}};

// CAnimationTrack (6 fields)
constexpr std::array<FieldDef, 6> kFields_CAnimationTrack{{
    FieldDef{"TrackName", "string"},
    FieldDef{"Channels", "link[]"},
    FieldDef{"CoordinateFrame", "uint"},
    FieldDef{"CoordinateFrameAxisX", "uint"},
    FieldDef{"CoordinateFrameAxisY", "uint"},
    FieldDef{"CoordinateFrameAxisZ", "uint"},
}};

// CBaseSettings (0 fields)
constexpr std::array<FieldDef, 0> kFields_CBaseSettings{};

// CCompilerBlobCache (6 fields)
constexpr std::array<FieldDef, 6> kFields_CCompilerBlobCache{{
    FieldDef{"ClassName", "string"},
    FieldDef{"Identifier", "uint"},
    FieldDef{"Blob", "unknown[]"},
    FieldDef{"Externals", "link[]"},
    FieldDef{"ExternalCalls", "link[]"},
    FieldDef{"EntryPoint", "link"},
}};

// CCompilerBlobCacheEntryPoint (3 fields)
constexpr std::array<FieldDef, 3> kFields_CCompilerBlobCacheEntryPoint{{
    FieldDef{"SymbolName", "string"},
    FieldDef{"BytecodeBegin", "uint"},
    FieldDef{"BytecodeEnd", "uint"},
}};

// CCompilerBlobCacheExternal (7 fields)
constexpr std::array<FieldDef, 7> kFields_CCompilerBlobCacheExternal{{
    FieldDef{"NameGUID", "string"},
    FieldDef{"TypeName", "string"},
    FieldDef{"NativeType", "uint"},
    FieldDef{"StorageSize", "uint"},
    FieldDef{"MetaType", "uint"},
    FieldDef{"Attributes", "uint"},
    FieldDef{"AccessMask", "uint"},
}};

// CCompilerBlobCacheFunctionArg (3 fields)
constexpr std::array<FieldDef, 3> kFields_CCompilerBlobCacheFunctionArg{{
    FieldDef{"Type", "uint"},
    FieldDef{"TypeName", "string"},
    FieldDef{"Attributes", "uint"},
}};

// CCompilerBlobCacheFunctionDef (4 fields)
constexpr std::array<FieldDef, 4> kFields_CCompilerBlobCacheFunctionDef{{
    FieldDef{"SymbolName", "string"},
    FieldDef{"SymbolSlot", "uint"},
    FieldDef{"FunctionTraits", "uint"},
    FieldDef{"Args", "link[]"},
}};

// CEditorAssetEffect (46 fields)
constexpr std::array<FieldDef, 46> kFields_CEditorAssetEffect{{
    FieldDef{"StartCameraPosition", "float3"},
    FieldDef{"StartCameraOrientation", "float3"},
    FieldDef{"MeshBackdrop", "bool"},
    FieldDef{"MeshPath", "string"},
    FieldDef{"MeshDiffusePath", "string"},
    FieldDef{"LightDirection", "float3"},
    FieldDef{"LightIntensity", "float"},
    FieldDef{"GridBackdrop", "bool"},
    FieldDef{"MeshBackdropVisible", "bool"},
    FieldDef{"MeshAnimPath", "string"},
    FieldDef{"AttribSamplerBindings", "string[]"},
    FieldDef{"LoopingEnabled", "bool"},
    FieldDef{"SoundBackdrop", "bool"},
    FieldDef{"SoundPath", "string"},
    FieldDef{"SoundVolume", "float"},
    FieldDef{"SoundAVSynchronisation", "bool"},
    FieldDef{"LoopDelay", "float"},
    FieldDef{"SpawnKeyboardRepeatRate", "float"},
    FieldDef{"BackgroundColorTop", "float3"},
    FieldDef{"BackgroundColorBottom", "float3"},
    FieldDef{"LoopDeterminismConstantSeed", "bool"},
    FieldDef{"MeshPosition", "float3"},
    FieldDef{"GridSize", "float"},
    FieldDef{"GridColor", "float4"},
    FieldDef{"GridSubColor", "float4"},
    FieldDef{"LightColor", "float3"},
    FieldDef{"AmbientColor", "float3"},
    FieldDef{"MeshOrientation", "float3"},
    FieldDef{"GridCollisions", "bool"},
    FieldDef{"MeshScale", "float3"},
    FieldDef{"GridPosition", "float3"},
    FieldDef{"AnimationBackdrop", "bool"},
    FieldDef{"AnimationPreset", "string"},
    FieldDef{"AnimSpeedModifier", "float"},
    FieldDef{"ApplyRotation", "bool"},
    FieldDef{"ApplyScale", "bool"},
    FieldDef{"GridSecondarySubdivisions", "int"},
    FieldDef{"WeightedSampling", "bool"},
    FieldDef{"WindBackdrop", "bool"},
    FieldDef{"WindConstantStrength", "float3"},
    FieldDef{"OccluderBackdrop", "bool"},
    FieldDef{"OccluderPosition", "float3"},
    FieldDef{"OccluderOrientation", "float3"},
    FieldDef{"OccluderSize", "float2"},
    FieldDef{"OccluderColor", "float4"},
    FieldDef{"BuildVersion", "string"},
}};

// CEngineRendererInterface (2 fields)
constexpr std::array<FieldDef, 2> kFields_CEngineRendererInterface{{
    FieldDef{"InterfaceName", "string"},
    FieldDef{"RendererFeatures", "link[]"},
}};

// CLayerCompileCache (24 fields)
constexpr std::array<FieldDef, 24> kFields_CLayerCompileCache{{
    FieldDef{"ConstantData", "uint4[]"},
    FieldDef{"RangeData", "uint4[]"},
    FieldDef{"Fields", "link[]"},
    FieldDef{"Attribs", "link[]"},
    FieldDef{"AttribSamplers", "link[]"},
    FieldDef{"Events", "link[]"},
    FieldDef{"SpatialLayers", "link[]"},
    FieldDef{"Samplers", "link[]"},
    FieldDef{"Renderers", "link[]"},
    FieldDef{"BlobCache_IR_TimeVarying", "link"},
    FieldDef{"BlobCache_IR_TimeFixed", "link[]"},
    FieldDef{"BlobCache_Backends", "link[]"},
    FieldDef{"RootEvent", "link"},
    FieldDef{"UsageFlags", "uint"},
    FieldDef{"HasEvolutionSideEffects", "bool"},
    FieldDef{"NeedsEvolveOnDeath", "bool"},
    FieldDef{"PreferredSimLocation", "int"},
    FieldDef{"PreferredStorageSize", "int"},
    FieldDef{"PreferredLocalization", "int"},
    FieldDef{"DeterminismEnabled", "bool"},
    FieldDef{"RandomSeedModifier", "uint"},
    FieldDef{"LODMetricOverride", "bool"},
    FieldDef{"LODDistanceMin", "float"},
    FieldDef{"LODDistanceMax", "float"},
}};

// CLayerCompileCacheAttrib (11 fields)
constexpr std::array<FieldDef, 11> kFields_CLayerCompileCacheAttrib{{
    FieldDef{"AttrName", "string"},
    FieldDef{"AttrDescription", "string_localized"},
    FieldDef{"AttrType", "uint"},
    FieldDef{"AttrDataSemantic", "int"},
    FieldDef{"AttrFlags", "uint"},
    FieldDef{"AttrMinI4", "int4"},
    FieldDef{"AttrMaxI4", "int4"},
    FieldDef{"AttrDefaultValueI4", "int4"},
    FieldDef{"AttrMinF4", "float4"},
    FieldDef{"AttrMaxF4", "float4"},
    FieldDef{"AttrDefaultValueF4", "float4"},
}};

// CLayerCompileCacheAttribSampler (6 fields)
constexpr std::array<FieldDef, 6> kFields_CLayerCompileCacheAttribSampler{{
    FieldDef{"AttrName", "string"},
    FieldDef{"AttrDescription", "string_localized"},
    FieldDef{"AttrDefaultDefinition", "link"},
    FieldDef{"AttrDefaultData", "string"},
    FieldDef{"AttrDefaultType", "int"},
    FieldDef{"AttrUsageFlags", "uint"},
}};

// CLayerCompileCacheEvent (4 fields)
constexpr std::array<FieldDef, 4> kFields_CLayerCompileCacheEvent{{
    FieldDef{"EventName", "string"},
    FieldDef{"EventFlags", "uint"},
    FieldDef{"EventPayload", "link[]"},
    FieldDef{"EventPayloadSizeInBytes", "uint"},
}};

// CLayerCompileCacheEventPayload (6 fields)
constexpr std::array<FieldDef, 6> kFields_CLayerCompileCacheEventPayload{{
    FieldDef{"PayloadName", "string"},
    FieldDef{"PayloadType", "uint"},
    FieldDef{"PayloadFootprintInBytes", "uint"},
    FieldDef{"PayloadFlags", "uint"},
    FieldDef{"PayloadKind", "uint"},
    FieldDef{"PayloadRangeSlot", "uint"},
}};

// CLayerCompileCacheField (6 fields)
constexpr std::array<FieldDef, 6> kFields_CLayerCompileCacheField{{
    FieldDef{"FieldName", "string"},
    FieldDef{"FieldType", "uint"},
    FieldDef{"FieldStorageSize", "uint"},
    FieldDef{"FieldFlags", "uint"},
    FieldDef{"FieldConstantSlot", "int"},
    FieldDef{"FieldRangeSlot", "int"},
}};

// CLayerCompileCacheRenderer (5 fields)
constexpr std::array<FieldDef, 5> kFields_CLayerCompileCacheRenderer{{
    FieldDef{"RendererClass", "int"},
    FieldDef{"Streams", "link[]"},
    FieldDef{"Properties", "link[]"},
    FieldDef{"FeatureSetPath", "string"},
    FieldDef{"DrawOrder", "int"},
}};

// CLayerCompileCacheRendererParticleInput (4 fields)
constexpr std::array<FieldDef, 4> kFields_CLayerCompileCacheRendererParticleInput{{
    FieldDef{"Semantic", "uint"},
    FieldDef{"IndexInStorage", "uint"},
    FieldDef{"AdditionalFieldName", "string"},
    FieldDef{"AdditionalFieldType", "int"},
}};

// CLayerCompileCacheRendererProperty (5 fields)
constexpr std::array<FieldDef, 5> kFields_CLayerCompileCacheRendererProperty{{
    FieldDef{"PropertyName", "string"},
    FieldDef{"PropertyType", "int"},
    FieldDef{"PropertyValueNumeric", "uint4"},
    FieldDef{"PropertyValueStr", "string"},
    FieldDef{"PropertySemantic", "int"},
}};

// CLayerCompileCacheSampler (5 fields)
constexpr std::array<FieldDef, 5> kFields_CLayerCompileCacheSampler{{
    FieldDef{"SamplerName", "string"},
    FieldDef{"Sampler", "link"},
    FieldDef{"SamplerData", "string"},
    FieldDef{"SamplerType", "int"},
    FieldDef{"SamplerUsageFlags", "uint"},
}};

// CLayerCompileCacheSpatialLayer (5 fields)
constexpr std::array<FieldDef, 5> kFields_CLayerCompileCacheSpatialLayer{{
    FieldDef{"SpatialLayerName", "string"},
    FieldDef{"SpatialLayerLocalName", "string"},
    FieldDef{"SpatialLayerFlags", "uint"},
    FieldDef{"SpatialLayerCellSize", "float"},
    FieldDef{"SpatialLayerPayload", "link[]"},
}};

// CLayerCompileCacheSpatialLayerPayload (3 fields)
constexpr std::array<FieldDef, 3> kFields_CLayerCompileCacheSpatialLayerPayload{{
    FieldDef{"PayloadName", "string"},
    FieldDef{"PayloadType", "uint"},
    FieldDef{"PayloadFlags", "uint"},
}};

// CLayerGraphCompileCache (6 fields)
constexpr std::array<FieldDef, 6> kFields_CLayerGraphCompileCache{{
    FieldDef{"EntryPointID", "int"},
    FieldDef{"EntrySlots", "link[]"},
    FieldDef{"LayerSlots", "link[]"},
    FieldDef{"EventSlots", "link[]"},
    FieldDef{"BroadSlots", "link[]"},
    FieldDef{"CoordinateSystem", "uint4"},
}};

// CLayerGraphCompileCache_BroadSlot (2 fields)
constexpr std::array<FieldDef, 2> kFields_CLayerGraphCompileCache_BroadSlot{{
    FieldDef{"BroadName", "string"},
    FieldDef{"ParentBroadSlots", "int[]"},
}};

// CLayerGraphCompileCache_EntrySlot (2 fields)
constexpr std::array<FieldDef, 2> kFields_CLayerGraphCompileCache_EntrySlot{{
    FieldDef{"EntryName", "string_unicode"},
    FieldDef{"EventSlot", "int"},
}};

// CLayerGraphCompileCache_EventSlot (4 fields)
constexpr std::array<FieldDef, 4> kFields_CLayerGraphCompileCache_EventSlot{{
    FieldDef{"EventName", "string"},
    FieldDef{"ParentLayerSlot", "int"},
    FieldDef{"LayerTargets", "int[]"},
    FieldDef{"BroadTargets", "int[]"},
}};

// CLayerGraphCompileCache_LayerSlot (3 fields)
constexpr std::array<FieldDef, 3> kFields_CLayerGraphCompileCache_LayerSlot{{
    FieldDef{"LayerCache", "link"},
    FieldDef{"ParentEventSlots", "int[]"},
    FieldDef{"EventSlots", "int[]"},
}};

// CParticleAttributeDeclaration (46 fields)
constexpr std::array<FieldDef, 46> kFields_CParticleAttributeDeclaration{{
    FieldDef{"ExportedName", "string"},
    FieldDef{"ExportedType", "int"},
    FieldDef{"CategoryName", "string_localized"},
    FieldDef{"Description", "string_localized"},
    FieldDef{"Semantic", "int"},
    FieldDef{"UseSlider", "bool"},
    FieldDef{"HasMin", "bool"},
    FieldDef{"HasMax", "bool"},
    FieldDef{"DefaultValueF1", "float"},
    FieldDef{"DefaultValueF2", "float2"},
    FieldDef{"DefaultValueF3", "float3"},
    FieldDef{"DefaultValueF3C", "float3"},
    FieldDef{"DefaultValueF3D", "float3"},
    FieldDef{"DefaultValueF4", "float4"},
    FieldDef{"DefaultValueF4C", "float4"},
    FieldDef{"DefaultValueI1", "int"},
    FieldDef{"DefaultValueI2", "int2"},
    FieldDef{"DefaultValueI3", "int3"},
    FieldDef{"DefaultValueI3D", "int3"},
    FieldDef{"DefaultValueI4", "int4"},
    FieldDef{"DefaultValueB1", "bool"},
    FieldDef{"DefaultValueB2", "bool2"},
    FieldDef{"DefaultValueB3", "bool3"},
    FieldDef{"DefaultValueB4", "bool4"},
    FieldDef{"DefaultValueO", "float3"},
    FieldDef{"MinValueF1", "float"},
    FieldDef{"MinValueF2", "float2"},
    FieldDef{"MinValueF3", "float3"},
    FieldDef{"MinValueF3D", "float3"},
    FieldDef{"MinValueF4", "float4"},
    FieldDef{"MinValueI1", "int"},
    FieldDef{"MinValueI2", "int2"},
    FieldDef{"MinValueI3", "int3"},
    FieldDef{"MinValueI3D", "int3"},
    FieldDef{"MinValueI4", "int4"},
    FieldDef{"MaxValueF1", "float"},
    FieldDef{"MaxValueF2", "float2"},
    FieldDef{"MaxValueF3", "float3"},
    FieldDef{"MaxValueF3D", "float3"},
    FieldDef{"MaxValueF4", "float4"},
    FieldDef{"MaxValueI1", "int"},
    FieldDef{"MaxValueI2", "int2"},
    FieldDef{"MaxValueI3", "int3"},
    FieldDef{"MaxValueI3D", "int3"},
    FieldDef{"MaxValueI4", "int4"},
    FieldDef{"Pinned", "bool"},
}};

// CParticleAttributeList (2 fields)
constexpr std::array<FieldDef, 2> kFields_CParticleAttributeList{{
    FieldDef{"AttributeList", "link[]"},
    FieldDef{"SamplerList", "link[]"},
}};

// CParticleAttributeSamplerDeclaration (7 fields)
constexpr std::array<FieldDef, 7> kFields_CParticleAttributeSamplerDeclaration{{
    FieldDef{"ExportedName", "string"},
    FieldDef{"ExportedType", "int"},
    FieldDef{"CategoryName", "string_localized"},
    FieldDef{"Description", "string_localized"},
    FieldDef{"Pinned", "bool"},
    FieldDef{"DefaultValue", "link"},
    FieldDef{"UsageFlags", "uint"},
}};

// CParticleEffect (10 fields)
constexpr std::array<FieldDef, 10> kFields_CParticleEffect{{
    FieldDef{"LayerGraph", "link"},
    FieldDef{"LayerGraphCompileCache", "link"},
    FieldDef{"Templates", "link[]"},
    FieldDef{"AttributeFlatList", "link"},
    FieldDef{"BoundsMode", "int"},
    FieldDef{"StaticBoundsMin", "float3"},
    FieldDef{"StaticBoundsMax", "float3"},
    FieldDef{"BoundScaleAttributeX", "string"},
    FieldDef{"BoundScaleAttributeY", "string"},
    FieldDef{"BoundScaleAttributeZ", "string"},
}};

// CParticleNode (9 fields)
constexpr std::array<FieldDef, 9> kFields_CParticleNode{{
    FieldDef{"CustomName", "string_localized"},
    FieldDef{"Description", "string_localized"},
    FieldDef{"Active", "bool"},
    FieldDef{"ExecStage", "uint"},
    FieldDef{"ExecFrequency", "uint"},
    FieldDef{"InputPins", "link[]"},
    FieldDef{"OutputPins", "link[]"},
    FieldDef{"WorkspacePosition", "int2"},
    FieldDef{"WorkspaceRollupState", "int"},
}};

// CParticleNodeAnnotation (12 fields)
constexpr std::array<FieldDef, 12> kFields_CParticleNodeAnnotation{{
    FieldDef{"CustomName", "string_localized"},
    FieldDef{"Description", "string_localized"},
    FieldDef{"Active", "bool"},
    FieldDef{"ExecStage", "uint"},
    FieldDef{"ExecFrequency", "uint"},
    FieldDef{"InputPins", "link[]"},
    FieldDef{"OutputPins", "link[]"},
    FieldDef{"WorkspacePosition", "int2"},
    FieldDef{"WorkspaceRollupState", "int"},
    FieldDef{"Color", "float4"},
    FieldDef{"Sticky", "bool"},
    FieldDef{"SelfSize", "int2"},
}};

// CParticleNodeArithmetic (10 fields)
constexpr std::array<FieldDef, 10> kFields_CParticleNodeArithmetic{{
    FieldDef{"CustomName", "string_localized"},
    FieldDef{"Description", "string_localized"},
    FieldDef{"Active", "bool"},
    FieldDef{"ExecStage", "uint"},
    FieldDef{"ExecFrequency", "uint"},
    FieldDef{"InputPins", "link[]"},
    FieldDef{"OutputPins", "link[]"},
    FieldDef{"WorkspacePosition", "int2"},
    FieldDef{"WorkspaceRollupState", "int"},
    FieldDef{"Operation", "uint"},
}};

// CParticleNodeAssign (9 fields)
constexpr std::array<FieldDef, 9> kFields_CParticleNodeAssign{{
    FieldDef{"CustomName", "string_localized"},
    FieldDef{"Description", "string_localized"},
    FieldDef{"Active", "bool"},
    FieldDef{"ExecStage", "uint"},
    FieldDef{"ExecFrequency", "uint"},
    FieldDef{"InputPins", "link[]"},
    FieldDef{"OutputPins", "link[]"},
    FieldDef{"WorkspacePosition", "int2"},
    FieldDef{"WorkspaceRollupState", "int"},
}};

// CParticleNodeCompare (10 fields)
constexpr std::array<FieldDef, 10> kFields_CParticleNodeCompare{{
    FieldDef{"CustomName", "string_localized"},
    FieldDef{"Description", "string_localized"},
    FieldDef{"Active", "bool"},
    FieldDef{"ExecStage", "uint"},
    FieldDef{"ExecFrequency", "uint"},
    FieldDef{"InputPins", "link[]"},
    FieldDef{"OutputPins", "link[]"},
    FieldDef{"WorkspacePosition", "int2"},
    FieldDef{"WorkspaceRollupState", "int"},
    FieldDef{"Operation", "uint"},
}};

// CParticleNodeConstant (30 fields)
constexpr std::array<FieldDef, 30> kFields_CParticleNodeConstant{{
    FieldDef{"CustomName", "string_localized"},
    FieldDef{"Description", "string_localized"},
    FieldDef{"Active", "bool"},
    FieldDef{"ExecStage", "uint"},
    FieldDef{"ExecFrequency", "uint"},
    FieldDef{"InputPins", "link[]"},
    FieldDef{"OutputPins", "link[]"},
    FieldDef{"WorkspacePosition", "int2"},
    FieldDef{"WorkspaceRollupState", "int"},
    FieldDef{"Type", "int"},
    FieldDef{"Semantic", "int"},
    FieldDef{"ValueF1", "float"},
    FieldDef{"ValueF2", "float2"},
    FieldDef{"ValueF3", "float3"},
    FieldDef{"ValueF4", "float4"},
    FieldDef{"ValueI1", "int"},
    FieldDef{"ValueI2", "int2"},
    FieldDef{"ValueI3", "int3"},
    FieldDef{"ValueI4", "int4"},
    FieldDef{"ValueB1", "bool"},
    FieldDef{"ValueB2", "bool2"},
    FieldDef{"ValueB3", "bool3"},
    FieldDef{"ValueB4", "bool4"},
    FieldDef{"ValueF3D", "float3"},
    FieldDef{"ValueF3C", "float3"},
    FieldDef{"ValueF4C", "float4"},
    FieldDef{"ValueI3D", "int3"},
    FieldDef{"ValueO", "float3"},
    FieldDef{"TransformSpace", "int"},
    FieldDef{"TransformMode", "int"},
}};

// CParticleNodeConstructor (11 fields)
constexpr std::array<FieldDef, 11> kFields_CParticleNodeConstructor{{
    FieldDef{"CustomName", "string_localized"},
    FieldDef{"Description", "string_localized"},
    FieldDef{"Active", "bool"},
    FieldDef{"ExecStage", "uint"},
    FieldDef{"ExecFrequency", "uint"},
    FieldDef{"InputPins", "link[]"},
    FieldDef{"OutputPins", "link[]"},
    FieldDef{"WorkspacePosition", "int2"},
    FieldDef{"WorkspaceRollupState", "int"},
    FieldDef{"Dimension", "uint"},
    FieldDef{"Mode", "int"},
}};

// CParticleNodeDebugCheck (11 fields)
constexpr std::array<FieldDef, 11> kFields_CParticleNodeDebugCheck{{
    FieldDef{"CustomName", "string_localized"},
    FieldDef{"Description", "string_localized"},
    FieldDef{"Active", "bool"},
    FieldDef{"ExecStage", "uint"},
    FieldDef{"ExecFrequency", "uint"},
    FieldDef{"InputPins", "link[]"},
    FieldDef{"OutputPins", "link[]"},
    FieldDef{"WorkspacePosition", "int2"},
    FieldDef{"WorkspaceRollupState", "int"},
    FieldDef{"Type", "int"},
    FieldDef{"Message", "string_unicode"},
}};

// CParticleNodeDiscretizationPoint (9 fields)
constexpr std::array<FieldDef, 9> kFields_CParticleNodeDiscretizationPoint{{
    FieldDef{"CustomName", "string_localized"},
    FieldDef{"Description", "string_localized"},
    FieldDef{"Active", "bool"},
    FieldDef{"ExecStage", "uint"},
    FieldDef{"ExecFrequency", "uint"},
    FieldDef{"InputPins", "link[]"},
    FieldDef{"OutputPins", "link[]"},
    FieldDef{"WorkspacePosition", "int2"},
    FieldDef{"WorkspaceRollupState", "int"},
}};

// CParticleNodeEvaluateAtSpawn (9 fields)
constexpr std::array<FieldDef, 9> kFields_CParticleNodeEvaluateAtSpawn{{
    FieldDef{"CustomName", "string_localized"},
    FieldDef{"Description", "string_localized"},
    FieldDef{"Active", "bool"},
    FieldDef{"ExecStage", "uint"},
    FieldDef{"ExecFrequency", "uint"},
    FieldDef{"InputPins", "link[]"},
    FieldDef{"OutputPins", "link[]"},
    FieldDef{"WorkspacePosition", "int2"},
    FieldDef{"WorkspaceRollupState", "int"},
}};

// CParticleNodeEventGenerator (9 fields)
constexpr std::array<FieldDef, 9> kFields_CParticleNodeEventGenerator{{
    FieldDef{"CustomName", "string_localized"},
    FieldDef{"Description", "string_localized"},
    FieldDef{"Active", "bool"},
    FieldDef{"ExecStage", "uint"},
    FieldDef{"ExecFrequency", "uint"},
    FieldDef{"InputPins", "link[]"},
    FieldDef{"OutputPins", "link[]"},
    FieldDef{"WorkspacePosition", "int2"},
    FieldDef{"WorkspaceRollupState", "int"},
}};

// CParticleNodeEventParent (9 fields)
constexpr std::array<FieldDef, 9> kFields_CParticleNodeEventParent{{
    FieldDef{"CustomName", "string_localized"},
    FieldDef{"Description", "string_localized"},
    FieldDef{"Active", "bool"},
    FieldDef{"ExecStage", "uint"},
    FieldDef{"ExecFrequency", "uint"},
    FieldDef{"InputPins", "link[]"},
    FieldDef{"OutputPins", "link[]"},
    FieldDef{"WorkspacePosition", "int2"},
    FieldDef{"WorkspaceRollupState", "int"},
}};

// CParticleNodeEventPayloadAppend (15 fields)
constexpr std::array<FieldDef, 15> kFields_CParticleNodeEventPayloadAppend{{
    FieldDef{"CustomName", "string_localized"},
    FieldDef{"Description", "string_localized"},
    FieldDef{"Active", "bool"},
    FieldDef{"ExecStage", "uint"},
    FieldDef{"ExecFrequency", "uint"},
    FieldDef{"InputPins", "link[]"},
    FieldDef{"OutputPins", "link[]"},
    FieldDef{"WorkspacePosition", "int2"},
    FieldDef{"WorkspaceRollupState", "int"},
    FieldDef{"PayloadName", "string"},
    FieldDef{"ForceOverride", "bool"},
    FieldDef{"IgnoreWarningsUnused", "bool"},
    FieldDef{"PayloadType", "string"},
    FieldDef{"PayloadKind", "int"},
    FieldDef{"Active2", "bool"},
}};

// CParticleNodeEventPayloadAppendBase (3 fields)
constexpr std::array<FieldDef, 3> kFields_CParticleNodeEventPayloadAppendBase{{
    FieldDef{"ForceOverride", "bool"},
    FieldDef{"ForceTypeOverride", "bool"},
    FieldDef{"IgnoreWarningsUnused", "bool"},
}};

// CParticleNodeEventPayloadAppendInterp (10 fields)
constexpr std::array<FieldDef, 10> kFields_CParticleNodeEventPayloadAppendInterp{{
    FieldDef{"CustomName", "string_localized"},
    FieldDef{"Description", "string_localized"},
    FieldDef{"Active", "bool"},
    FieldDef{"ExecStage", "uint"},
    FieldDef{"ExecFrequency", "uint"},
    FieldDef{"InputPins", "link[]"},
    FieldDef{"OutputPins", "link[]"},
    FieldDef{"WorkspacePosition", "int2"},
    FieldDef{"WorkspaceRollupState", "int"},
    FieldDef{"Interpolation", "int"},
}};

// CParticleNodeEventPayloadBase (3 fields)
constexpr std::array<FieldDef, 3> kFields_CParticleNodeEventPayloadBase{{
    FieldDef{"PayloadName", "string"},
    FieldDef{"PayloadType", "int"},
    FieldDef{"PayloadKind", "int"},
}};

// CParticleNodeEventPayloadClear (11 fields)
constexpr std::array<FieldDef, 11> kFields_CParticleNodeEventPayloadClear{{
    FieldDef{"CustomName", "string_localized"},
    FieldDef{"Description", "string_localized"},
    FieldDef{"Active", "bool"},
    FieldDef{"ExecStage", "uint"},
    FieldDef{"ExecFrequency", "uint"},
    FieldDef{"InputPins", "link[]"},
    FieldDef{"OutputPins", "link[]"},
    FieldDef{"WorkspacePosition", "int2"},
    FieldDef{"WorkspaceRollupState", "int"},
    FieldDef{"ClearAll", "bool"},
    FieldDef{"PayloadName", "string"},
}};

// CParticleNodeEventPayloadCopy (9 fields)
constexpr std::array<FieldDef, 9> kFields_CParticleNodeEventPayloadCopy{{
    FieldDef{"CustomName", "string_localized"},
    FieldDef{"Description", "string_localized"},
    FieldDef{"Active", "bool"},
    FieldDef{"ExecStage", "uint"},
    FieldDef{"ExecFrequency", "uint"},
    FieldDef{"InputPins", "link[]"},
    FieldDef{"OutputPins", "link[]"},
    FieldDef{"WorkspacePosition", "int2"},
    FieldDef{"WorkspaceRollupState", "int"},
}};

// CParticleNodeEventPayloadExtract (13 fields)
constexpr std::array<FieldDef, 13> kFields_CParticleNodeEventPayloadExtract{{
    FieldDef{"CustomName", "string_localized"},
    FieldDef{"Description", "string_localized"},
    FieldDef{"Active", "bool"},
    FieldDef{"ExecStage", "uint"},
    FieldDef{"ExecFrequency", "uint"},
    FieldDef{"InputPins", "link[]"},
    FieldDef{"OutputPins", "link[]"},
    FieldDef{"WorkspacePosition", "int2"},
    FieldDef{"WorkspaceRollupState", "int"},
    FieldDef{"PayloadName", "string"},
    FieldDef{"PayloadType", "string"},
    FieldDef{"PayloadKind", "int"},
    FieldDef{"IgnoreWarningsMissing", "bool"},
}};

// CParticleNodeEventPayloadExtractBase (3 fields)
constexpr std::array<FieldDef, 3> kFields_CParticleNodeEventPayloadExtractBase{{
    FieldDef{"IgnoreWarningsMissing", "bool"},
    FieldDef{"ExtractEventMask", "bool"},
    FieldDef{"RemoveFromPayload", "bool"},
}};

// CParticleNodeEventPayloadExtractInterp (10 fields)
constexpr std::array<FieldDef, 10> kFields_CParticleNodeEventPayloadExtractInterp{{
    FieldDef{"CustomName", "string_localized"},
    FieldDef{"Description", "string_localized"},
    FieldDef{"Active", "bool"},
    FieldDef{"ExecStage", "uint"},
    FieldDef{"ExecFrequency", "uint"},
    FieldDef{"InputPins", "link[]"},
    FieldDef{"OutputPins", "link[]"},
    FieldDef{"WorkspacePosition", "int2"},
    FieldDef{"WorkspaceRollupState", "int"},
    FieldDef{"PayloadName", "string"},
}};

// CParticleNodeEventStart (10 fields)
constexpr std::array<FieldDef, 10> kFields_CParticleNodeEventStart{{
    FieldDef{"CustomName", "string_localized"},
    FieldDef{"Description", "string_localized"},
    FieldDef{"Active", "bool"},
    FieldDef{"ExecStage", "uint"},
    FieldDef{"ExecFrequency", "uint"},
    FieldDef{"InputPins", "link[]"},
    FieldDef{"OutputPins", "link[]"},
    FieldDef{"WorkspacePosition", "int2"},
    FieldDef{"WorkspaceRollupState", "int"},
    FieldDef{"EventName", "string_unicode"},
}};

// CParticleNodeEventTrigger (9 fields)
constexpr std::array<FieldDef, 9> kFields_CParticleNodeEventTrigger{{
    FieldDef{"CustomName", "string_localized"},
    FieldDef{"Description", "string_localized"},
    FieldDef{"Active", "bool"},
    FieldDef{"ExecStage", "uint"},
    FieldDef{"ExecFrequency", "uint"},
    FieldDef{"InputPins", "link[]"},
    FieldDef{"OutputPins", "link[]"},
    FieldDef{"WorkspacePosition", "int2"},
    FieldDef{"WorkspaceRollupState", "int"},
}};

// CParticleNodeGraph (15 fields)
constexpr std::array<FieldDef, 15> kFields_CParticleNodeGraph{{
    FieldDef{"CustomName", "string_unicode"},
    FieldDef{"Description", "string_localized"},
    FieldDef{"Public", "bool"},
    FieldDef{"SimulationInterface", "bool"},
    FieldDef{"AutoInline", "bool"},
    FieldDef{"ClassType", "uint"},
    FieldDef{"IconKey", "string"},
    FieldDef{"Category", "string"},
    FieldDef{"SearchKeywords", "string_unicode"},
    FieldDef{"Nodes", "link[]"},
    FieldDef{"Timeline", "link"},
    FieldDef{"WorkspacePosition", "int2"},
    FieldDef{"WorkspaceZoom", "int"},
    FieldDef{"GraphType", "int"},
    FieldDef{"Collapsed", "bool"},
}};

// CParticleNodeIf (9 fields)
constexpr std::array<FieldDef, 9> kFields_CParticleNodeIf{{
    FieldDef{"CustomName", "string_localized"},
    FieldDef{"Description", "string_localized"},
    FieldDef{"Active", "bool"},
    FieldDef{"ExecStage", "uint"},
    FieldDef{"ExecFrequency", "uint"},
    FieldDef{"InputPins", "link[]"},
    FieldDef{"OutputPins", "link[]"},
    FieldDef{"WorkspacePosition", "int2"},
    FieldDef{"WorkspaceRollupState", "int"},
}};

// CParticleNodeIntegrate (10 fields)
constexpr std::array<FieldDef, 10> kFields_CParticleNodeIntegrate{{
    FieldDef{"CustomName", "string_localized"},
    FieldDef{"Description", "string_localized"},
    FieldDef{"Active", "bool"},
    FieldDef{"ExecStage", "uint"},
    FieldDef{"ExecFrequency", "uint"},
    FieldDef{"InputPins", "link[]"},
    FieldDef{"OutputPins", "link[]"},
    FieldDef{"WorkspacePosition", "int2"},
    FieldDef{"WorkspaceRollupState", "int"},
    FieldDef{"Base", "uint"},
}};

// CParticleNodeLayer (19 fields)
constexpr std::array<FieldDef, 19> kFields_CParticleNodeLayer{{
    FieldDef{"CustomName", "string_localized"},
    FieldDef{"Description", "string_localized"},
    FieldDef{"Active", "bool"},
    FieldDef{"ExecStage", "uint"},
    FieldDef{"ExecFrequency", "uint"},
    FieldDef{"InputPins", "link[]"},
    FieldDef{"OutputPins", "link[]"},
    FieldDef{"WorkspacePosition", "int2"},
    FieldDef{"WorkspaceRollupState", "int"},
    FieldDef{"AutoEntrypoint", "bool"},
    FieldDef{"LODMetricOverride", "bool"},
    FieldDef{"LODDistanceMin", "float"},
    FieldDef{"LODDistanceMax", "float"},
    FieldDef{"PreferredSimLocation", "int"},
    FieldDef{"PreferredStorageSize", "int"},
    FieldDef{"PreferredLocalization", "int"},
    FieldDef{"Determinism", "int"},
    FieldDef{"RandomSeedModifier", "int"},
    FieldDef{"NodeGraph", "link"},
}};

// CParticleNodeMathFunction1 (11 fields)
constexpr std::array<FieldDef, 11> kFields_CParticleNodeMathFunction1{{
    FieldDef{"CustomName", "string_localized"},
    FieldDef{"Description", "string_localized"},
    FieldDef{"Active", "bool"},
    FieldDef{"ExecStage", "uint"},
    FieldDef{"ExecFrequency", "uint"},
    FieldDef{"InputPins", "link[]"},
    FieldDef{"OutputPins", "link[]"},
    FieldDef{"WorkspacePosition", "int2"},
    FieldDef{"WorkspaceRollupState", "int"},
    FieldDef{"Function", "uint"},
    FieldDef{"AngleUnit", "int"},
}};

// CParticleNodeMathFunction2 (11 fields)
constexpr std::array<FieldDef, 11> kFields_CParticleNodeMathFunction2{{
    FieldDef{"CustomName", "string_localized"},
    FieldDef{"Description", "string_localized"},
    FieldDef{"Active", "bool"},
    FieldDef{"ExecStage", "uint"},
    FieldDef{"ExecFrequency", "uint"},
    FieldDef{"InputPins", "link[]"},
    FieldDef{"OutputPins", "link[]"},
    FieldDef{"WorkspacePosition", "int2"},
    FieldDef{"WorkspaceRollupState", "int"},
    FieldDef{"Function", "uint"},
    FieldDef{"AngleUnit", "int"},
}};

// CParticleNodeMathFunction3 (10 fields)
constexpr std::array<FieldDef, 10> kFields_CParticleNodeMathFunction3{{
    FieldDef{"CustomName", "string_localized"},
    FieldDef{"Description", "string_localized"},
    FieldDef{"Active", "bool"},
    FieldDef{"ExecStage", "uint"},
    FieldDef{"ExecFrequency", "uint"},
    FieldDef{"InputPins", "link[]"},
    FieldDef{"OutputPins", "link[]"},
    FieldDef{"WorkspacePosition", "int2"},
    FieldDef{"WorkspaceRollupState", "int"},
    FieldDef{"Function", "uint"},
}};

// CParticleNodeMathWaveform (10 fields)
constexpr std::array<FieldDef, 10> kFields_CParticleNodeMathWaveform{{
    FieldDef{"CustomName", "string_localized"},
    FieldDef{"Description", "string_localized"},
    FieldDef{"Active", "bool"},
    FieldDef{"ExecStage", "uint"},
    FieldDef{"ExecFrequency", "uint"},
    FieldDef{"InputPins", "link[]"},
    FieldDef{"OutputPins", "link[]"},
    FieldDef{"WorkspacePosition", "int2"},
    FieldDef{"WorkspaceRollupState", "int"},
    FieldDef{"Waveform", "uint"},
}};

// CParticleNodePartialDerivative (10 fields)
constexpr std::array<FieldDef, 10> kFields_CParticleNodePartialDerivative{{
    FieldDef{"CustomName", "string_localized"},
    FieldDef{"Description", "string_localized"},
    FieldDef{"Active", "bool"},
    FieldDef{"ExecStage", "uint"},
    FieldDef{"ExecFrequency", "uint"},
    FieldDef{"InputPins", "link[]"},
    FieldDef{"OutputPins", "link[]"},
    FieldDef{"WorkspacePosition", "int2"},
    FieldDef{"WorkspaceRollupState", "int"},
    FieldDef{"Base", "uint"},
}};

// CParticleNodePassThrough (9 fields)
constexpr std::array<FieldDef, 9> kFields_CParticleNodePassThrough{{
    FieldDef{"CustomName", "string_localized"},
    FieldDef{"Description", "string_localized"},
    FieldDef{"Active", "bool"},
    FieldDef{"ExecStage", "uint"},
    FieldDef{"ExecFrequency", "uint"},
    FieldDef{"InputPins", "link[]"},
    FieldDef{"OutputPins", "link[]"},
    FieldDef{"WorkspacePosition", "int2"},
    FieldDef{"WorkspaceRollupState", "int"},
}};

// CParticleNodePinAbstract (5 fields)
constexpr std::array<FieldDef, 5> kFields_CParticleNodePinAbstract{{
    FieldDef{"SelfName", "string"},
    FieldDef{"Type", "int"},
    FieldDef{"Visible", "bool"},
    FieldDef{"Owner", "link"},
    FieldDef{"BaseType", "int"},
}};

// CParticleNodePinIn (11 fields)
constexpr std::array<FieldDef, 11> kFields_CParticleNodePinIn{{
    FieldDef{"SelfName", "string"},
    FieldDef{"Type", "string"},
    FieldDef{"Visible", "bool"},
    FieldDef{"Owner", "link"},
    FieldDef{"BaseType", "string"},
    FieldDef{"ConnectedPins", "link[]"},
    FieldDef{"ValueF", "float4"},
    FieldDef{"ValueI", "int4"},
    FieldDef{"ValueB", "bool4"},
    FieldDef{"ValueD", "string"},
    FieldDef{"ExportInParent", "bool"},
}};

// CParticleNodePinOut (6 fields)
constexpr std::array<FieldDef, 6> kFields_CParticleNodePinOut{{
    FieldDef{"SelfName", "string"},
    FieldDef{"Type", "string"},
    FieldDef{"Visible", "bool"},
    FieldDef{"Owner", "link"},
    FieldDef{"BaseType", "string"},
    FieldDef{"ConnectedPins", "link[]"},
}};

// CParticleNodeReinterpret (10 fields)
constexpr std::array<FieldDef, 10> kFields_CParticleNodeReinterpret{{
    FieldDef{"CustomName", "string_localized"},
    FieldDef{"Description", "string_localized"},
    FieldDef{"Active", "bool"},
    FieldDef{"ExecStage", "uint"},
    FieldDef{"ExecFrequency", "uint"},
    FieldDef{"InputPins", "link[]"},
    FieldDef{"OutputPins", "link[]"},
    FieldDef{"WorkspacePosition", "int2"},
    FieldDef{"WorkspaceRollupState", "int"},
    FieldDef{"TargetType", "int"},
}};

// CParticleNodeRendererBase (3 fields)
constexpr std::array<FieldDef, 3> kFields_CParticleNodeRendererBase{{
    FieldDef{"FeatureSetPath", "string"},
    FieldDef{"DrawOrder", "int"},
    FieldDef{"RendererFeatures", "string[]"},
}};

// CParticleNodeRendererBillboard (12 fields)
constexpr std::array<FieldDef, 12> kFields_CParticleNodeRendererBillboard{{
    FieldDef{"CustomName", "string_localized"},
    FieldDef{"Description", "string_localized"},
    FieldDef{"Active", "bool"},
    FieldDef{"ExecStage", "uint"},
    FieldDef{"ExecFrequency", "uint"},
    FieldDef{"InputPins", "link[]"},
    FieldDef{"OutputPins", "link[]"},
    FieldDef{"WorkspacePosition", "int2"},
    FieldDef{"WorkspaceRollupState", "int"},
    FieldDef{"FeatureSetPath", "string"},
    FieldDef{"RendererFeatures", "link[]"},
    FieldDef{"DrawOrder", "int"},
}};

// CParticleNodeRendererLight (11 fields)
constexpr std::array<FieldDef, 11> kFields_CParticleNodeRendererLight{{
    FieldDef{"CustomName", "string_localized"},
    FieldDef{"Description", "string_localized"},
    FieldDef{"Active", "bool"},
    FieldDef{"ExecStage", "uint"},
    FieldDef{"ExecFrequency", "uint"},
    FieldDef{"InputPins", "link[]"},
    FieldDef{"OutputPins", "link[]"},
    FieldDef{"WorkspacePosition", "int2"},
    FieldDef{"WorkspaceRollupState", "int"},
    FieldDef{"FeatureSetPath", "string"},
    FieldDef{"RendererFeatures", "link[]"},
}};

// CParticleNodeRendererMesh (11 fields)
constexpr std::array<FieldDef, 11> kFields_CParticleNodeRendererMesh{{
    FieldDef{"CustomName", "string_localized"},
    FieldDef{"Description", "string_localized"},
    FieldDef{"Active", "bool"},
    FieldDef{"ExecStage", "uint"},
    FieldDef{"ExecFrequency", "uint"},
    FieldDef{"InputPins", "link[]"},
    FieldDef{"OutputPins", "link[]"},
    FieldDef{"WorkspacePosition", "int2"},
    FieldDef{"WorkspaceRollupState", "int"},
    FieldDef{"FeatureSetPath", "string"},
    FieldDef{"RendererFeatures", "link[]"},
}};

// CParticleNodeRendererRibbon (11 fields)
constexpr std::array<FieldDef, 11> kFields_CParticleNodeRendererRibbon{{
    FieldDef{"CustomName", "string_localized"},
    FieldDef{"Description", "string_localized"},
    FieldDef{"Active", "bool"},
    FieldDef{"ExecStage", "uint"},
    FieldDef{"ExecFrequency", "uint"},
    FieldDef{"InputPins", "link[]"},
    FieldDef{"OutputPins", "link[]"},
    FieldDef{"WorkspacePosition", "int2"},
    FieldDef{"WorkspaceRollupState", "int"},
    FieldDef{"FeatureSetPath", "string"},
    FieldDef{"RendererFeatures", "link[]"},
}};

// CParticleNodeRendererSound (11 fields)
constexpr std::array<FieldDef, 11> kFields_CParticleNodeRendererSound{{
    FieldDef{"CustomName", "string_localized"},
    FieldDef{"Description", "string_localized"},
    FieldDef{"Active", "bool"},
    FieldDef{"ExecStage", "uint"},
    FieldDef{"ExecFrequency", "uint"},
    FieldDef{"InputPins", "link[]"},
    FieldDef{"OutputPins", "link[]"},
    FieldDef{"WorkspacePosition", "int2"},
    FieldDef{"WorkspaceRollupState", "int"},
    FieldDef{"FeatureSetPath", "string"},
    FieldDef{"RendererFeatures", "link[]"},
}};

// CParticleNodeSamplerData (9 fields)
constexpr std::array<FieldDef, 9> kFields_CParticleNodeSamplerData{{
    FieldDef{"CustomName", "string_localized"},
    FieldDef{"Description", "string_localized"},
    FieldDef{"Active", "bool"},
    FieldDef{"ExecStage", "uint"},
    FieldDef{"ExecFrequency", "uint"},
    FieldDef{"InputPins", "link[]"},
    FieldDef{"OutputPins", "link[]"},
    FieldDef{"WorkspacePosition", "int2"},
    FieldDef{"WorkspaceRollupState", "int"},
}};

// CParticleNodeSamplerData_AnimTrack (16 fields)
constexpr std::array<FieldDef, 16> kFields_CParticleNodeSamplerData_AnimTrack{{
    FieldDef{"CustomName", "string_localized"},
    FieldDef{"Description", "string_localized"},
    FieldDef{"Active", "bool"},
    FieldDef{"ExecStage", "uint"},
    FieldDef{"ExecFrequency", "uint"},
    FieldDef{"InputPins", "link[]"},
    FieldDef{"OutputPins", "link[]"},
    FieldDef{"WorkspacePosition", "int2"},
    FieldDef{"WorkspaceRollupState", "int"},
    FieldDef{"AnimResource", "string"},
    FieldDef{"TransformTranslate", "bool"},
    FieldDef{"TransformRotate", "bool"},
    FieldDef{"TransformScale", "bool"},
    FieldDef{"Position", "float3"},
    FieldDef{"EulerOrientation", "float3"},
    FieldDef{"Scale", "float3"},
}};

// CParticleNodeSamplerData_Audio (11 fields)
constexpr std::array<FieldDef, 11> kFields_CParticleNodeSamplerData_Audio{{
    FieldDef{"CustomName", "string_localized"},
    FieldDef{"Description", "string_localized"},
    FieldDef{"Active", "bool"},
    FieldDef{"ExecStage", "uint"},
    FieldDef{"ExecFrequency", "uint"},
    FieldDef{"InputPins", "link[]"},
    FieldDef{"OutputPins", "link[]"},
    FieldDef{"WorkspacePosition", "int2"},
    FieldDef{"WorkspaceRollupState", "int"},
    FieldDef{"ChannelGroup", "string"},
    FieldDef{"Mode", "uint"},
}};

// CParticleNodeSamplerData_Curve (19 fields)
constexpr std::array<FieldDef, 19> kFields_CParticleNodeSamplerData_Curve{{
    FieldDef{"CustomName", "string_localized"},
    FieldDef{"Description", "string_localized"},
    FieldDef{"Active", "bool"},
    FieldDef{"ExecStage", "uint"},
    FieldDef{"ExecFrequency", "uint"},
    FieldDef{"InputPins", "link[]"},
    FieldDef{"OutputPins", "link[]"},
    FieldDef{"WorkspacePosition", "int2"},
    FieldDef{"WorkspaceRollupState", "int"},
    FieldDef{"ValueType", "uint"},
    FieldDef{"Interpolator", "uint"},
    FieldDef{"MinLimits", "float4"},
    FieldDef{"MaxLimits", "float4"},
    FieldDef{"IsProbabilityCurve", "bool"},
    FieldDef{"Quality", "uint"},
    FieldDef{"IsLoopedCurve", "bool"},
    FieldDef{"Times", "float[]"},
    FieldDef{"FloatValues", "float[]"},
    FieldDef{"FloatTangents", "float[]"},
}};

// CParticleNodeSamplerData_DoubleCurve (19 fields)
constexpr std::array<FieldDef, 19> kFields_CParticleNodeSamplerData_DoubleCurve{{
    FieldDef{"CustomName", "string_localized"},
    FieldDef{"Description", "string_localized"},
    FieldDef{"Active", "bool"},
    FieldDef{"ExecStage", "uint"},
    FieldDef{"ExecFrequency", "uint"},
    FieldDef{"InputPins", "link[]"},
    FieldDef{"OutputPins", "link[]"},
    FieldDef{"WorkspacePosition", "int2"},
    FieldDef{"WorkspaceRollupState", "int"},
    FieldDef{"ValueType", "uint"},
    FieldDef{"Interpolator", "uint"},
    FieldDef{"MinLimits", "float4"},
    FieldDef{"MaxLimits", "float4"},
    FieldDef{"Times", "float[]"},
    FieldDef{"FloatValues", "float[]"},
    FieldDef{"FloatTangents", "float[]"},
    FieldDef{"Times1", "float[]"},
    FieldDef{"FloatValues1", "float[]"},
    FieldDef{"FloatTangents1", "float[]"},
}};

// CParticleNodeSamplerData_EventStream (12 fields)
constexpr std::array<FieldDef, 12> kFields_CParticleNodeSamplerData_EventStream{{
    FieldDef{"CustomName", "string_localized"},
    FieldDef{"Description", "string_localized"},
    FieldDef{"Active", "bool"},
    FieldDef{"ExecStage", "uint"},
    FieldDef{"ExecFrequency", "uint"},
    FieldDef{"InputPins", "link[]"},
    FieldDef{"OutputPins", "link[]"},
    FieldDef{"WorkspacePosition", "int2"},
    FieldDef{"WorkspaceRollupState", "int"},
    FieldDef{"EventSource", "int"},
    FieldDef{"Times", "float[]"},
    FieldDef{"Payload", "link[]"},
}};

// CParticleNodeSamplerData_EventStream_Payload (6 fields)
constexpr std::array<FieldDef, 6> kFields_CParticleNodeSamplerData_EventStream_Payload{{
    FieldDef{"Description", "string_unicode"},
    FieldDef{"SelfName", "string"},
    FieldDef{"Type", "int"},
    FieldDef{"ValuesF4", "float4[]"},
    FieldDef{"ValuesI4", "int4[]"},
    FieldDef{"ValuesB4", "bool4[]"},
}};

// CParticleNodeSamplerData_Shape (31 fields)
constexpr std::array<FieldDef, 31> kFields_CParticleNodeSamplerData_Shape{{
    FieldDef{"CustomName", "string_localized"},
    FieldDef{"Description", "string_localized"},
    FieldDef{"Active", "bool"},
    FieldDef{"ExecStage", "uint"},
    FieldDef{"ExecFrequency", "uint"},
    FieldDef{"InputPins", "link[]"},
    FieldDef{"OutputPins", "link[]"},
    FieldDef{"WorkspacePosition", "int2"},
    FieldDef{"WorkspaceRollupState", "int"},
    FieldDef{"SampleDimensionality", "uint"},
    FieldDef{"TransformTranslate", "bool"},
    FieldDef{"TransformRotate", "bool"},
    FieldDef{"Weight", "float"},
    FieldDef{"Position", "float3"},
    FieldDef{"EulerOrientation", "float3"},
    FieldDef{"ShapeType", "int"},
    FieldDef{"BoxDimensions", "float3"},
    FieldDef{"Radius", "float"},
    FieldDef{"InnerRadius", "float"},
    FieldDef{"NormalizedInnerRadius", "float"},
    FieldDef{"Height", "float"},
    FieldDef{"Hemisphere", "bool"},
    FieldDef{"NonUniformScale", "float3"},
    FieldDef{"MeshResource", "string"},
    FieldDef{"MeshScale", "float3"},
    FieldDef{"MeshSamplingMode", "uint"},
    FieldDef{"SubMeshIndex", "uint"},
    FieldDef{"DefaultUvStream", "uint"},
    FieldDef{"DefaultColorStream", "uint"},
    FieldDef{"DensityColorStream", "uint"},
    FieldDef{"DensityChannel", "uint"},
}};

// CParticleNodeSamplerData_Text (14 fields)
constexpr std::array<FieldDef, 14> kFields_CParticleNodeSamplerData_Text{{
    FieldDef{"CustomName", "string_localized"},
    FieldDef{"Description", "string_localized"},
    FieldDef{"Active", "bool"},
    FieldDef{"ExecStage", "uint"},
    FieldDef{"ExecFrequency", "uint"},
    FieldDef{"InputPins", "link[]"},
    FieldDef{"OutputPins", "link[]"},
    FieldDef{"WorkspacePosition", "int2"},
    FieldDef{"WorkspaceRollupState", "int"},
    FieldDef{"DataSource", "uint"},
    FieldDef{"InlineText", "string"},
    FieldDef{"ExternalResource", "string"},
    FieldDef{"FontFile", "string"},
    FieldDef{"UseKerning", "bool"},
}};

// CParticleNodeSamplerData_Texture (17 fields)
constexpr std::array<FieldDef, 17> kFields_CParticleNodeSamplerData_Texture{{
    FieldDef{"CustomName", "string_localized"},
    FieldDef{"Description", "string_localized"},
    FieldDef{"Active", "bool"},
    FieldDef{"ExecStage", "uint"},
    FieldDef{"ExecFrequency", "uint"},
    FieldDef{"InputPins", "link[]"},
    FieldDef{"OutputPins", "link[]"},
    FieldDef{"WorkspacePosition", "int2"},
    FieldDef{"WorkspaceRollupState", "int"},
    FieldDef{"TextureResource", "string"},
    FieldDef{"AtlasDefinition", "string"},
    FieldDef{"ScriptOutputType", "uint"},
    FieldDef{"SampleRawValues", "bool"},
    FieldDef{"SampleGammaSpace", "uint"},
    FieldDef{"DensityPower", "float"},
    FieldDef{"DensitySrc", "uint"},
    FieldDef{"DensityRGBAWeights", "float4"},
}};

// CParticleNodeSamplerData_Turbulence (31 fields)
constexpr std::array<FieldDef, 31> kFields_CParticleNodeSamplerData_Turbulence{{
    FieldDef{"CustomName", "string_localized"},
    FieldDef{"Description", "string_localized"},
    FieldDef{"Active", "bool"},
    FieldDef{"ExecStage", "uint"},
    FieldDef{"ExecFrequency", "uint"},
    FieldDef{"InputPins", "link[]"},
    FieldDef{"OutputPins", "link[]"},
    FieldDef{"WorkspacePosition", "int2"},
    FieldDef{"WorkspaceRollupState", "int"},
    FieldDef{"DataSource", "uint"},
    FieldDef{"VectorFieldResource", "string"},
    FieldDef{"GlobalScale", "float"},
    FieldDef{"Strength", "float"},
    FieldDef{"WrapSide", "bool"},
    FieldDef{"WrapVertical", "bool"},
    FieldDef{"WrapDepth", "bool"},
    FieldDef{"WrapTime", "bool"},
    FieldDef{"Filtering", "int"},
    FieldDef{"Wavelength", "float"},
    FieldDef{"Octaves", "uint"},
    FieldDef{"Lacunarity", "float"},
    FieldDef{"Gain", "float"},
    FieldDef{"Interpolator", "int"},
    FieldDef{"TimeScale", "float"},
    FieldDef{"TimeBase", "float"},
    FieldDef{"TimeRandomVariation", "float"},
    FieldDef{"FlowFactor", "float"},
    FieldDef{"DivergenceFactor", "float"},
    FieldDef{"InitialSeed", "uint"},
    FieldDef{"FastFakeFlow", "bool"},
    FieldDef{"GainMultiplier", "float"},
}};

// CParticleNodeScript (10 fields)
constexpr std::array<FieldDef, 10> kFields_CParticleNodeScript{{
    FieldDef{"CustomName", "string_localized"},
    FieldDef{"Description", "string_localized"},
    FieldDef{"Active", "bool"},
    FieldDef{"ExecStage", "uint"},
    FieldDef{"ExecFrequency", "uint"},
    FieldDef{"InputPins", "link[]"},
    FieldDef{"OutputPins", "link[]"},
    FieldDef{"WorkspacePosition", "int2"},
    FieldDef{"WorkspaceRollupState", "int"},
    FieldDef{"Expression", "string_unicode"},
}};

// CParticleNodeSetLife (9 fields)
constexpr std::array<FieldDef, 9> kFields_CParticleNodeSetLife{{
    FieldDef{"CustomName", "string_localized"},
    FieldDef{"Description", "string_localized"},
    FieldDef{"Active", "bool"},
    FieldDef{"ExecStage", "uint"},
    FieldDef{"ExecFrequency", "uint"},
    FieldDef{"InputPins", "link[]"},
    FieldDef{"OutputPins", "link[]"},
    FieldDef{"WorkspacePosition", "int2"},
    FieldDef{"WorkspaceRollupState", "int"},
}};

// CParticleNodeSpatialInsert (9 fields)
constexpr std::array<FieldDef, 9> kFields_CParticleNodeSpatialInsert{{
    FieldDef{"CustomName", "string_localized"},
    FieldDef{"Description", "string_localized"},
    FieldDef{"Active", "bool"},
    FieldDef{"ExecStage", "uint"},
    FieldDef{"ExecFrequency", "uint"},
    FieldDef{"InputPins", "link[]"},
    FieldDef{"OutputPins", "link[]"},
    FieldDef{"WorkspacePosition", "int2"},
    FieldDef{"WorkspaceRollupState", "int"},
}};

// CParticleNodeSpatialLayer (13 fields)
constexpr std::array<FieldDef, 13> kFields_CParticleNodeSpatialLayer{{
    FieldDef{"CustomName", "string_localized"},
    FieldDef{"Description", "string_localized"},
    FieldDef{"Active", "bool"},
    FieldDef{"ExecStage", "uint"},
    FieldDef{"ExecFrequency", "uint"},
    FieldDef{"InputPins", "link[]"},
    FieldDef{"OutputPins", "link[]"},
    FieldDef{"WorkspacePosition", "int2"},
    FieldDef{"WorkspaceRollupState", "int"},
    FieldDef{"SelfName", "string"},
    FieldDef{"Global", "bool"},
    FieldDef{"CellSize", "float"},
    FieldDef{"Storage", "link[]"},
}};

// CParticleNodeSpatialLayerStorage (3 fields)
constexpr std::array<FieldDef, 3> kFields_CParticleNodeSpatialLayerStorage{{
    FieldDef{"Description", "string_unicode"},
    FieldDef{"SelfName", "string"},
    FieldDef{"Type", "int"},
}};

// CParticleNodeSpatialPayloadAppend (13 fields)
constexpr std::array<FieldDef, 13> kFields_CParticleNodeSpatialPayloadAppend{{
    FieldDef{"CustomName", "string_localized"},
    FieldDef{"Description", "string_localized"},
    FieldDef{"Active", "bool"},
    FieldDef{"ExecStage", "uint"},
    FieldDef{"ExecFrequency", "uint"},
    FieldDef{"InputPins", "link[]"},
    FieldDef{"OutputPins", "link[]"},
    FieldDef{"WorkspacePosition", "int2"},
    FieldDef{"WorkspaceRollupState", "int"},
    FieldDef{"PayloadName", "string"},
    FieldDef{"PayloadType", "int"},
    FieldDef{"ForceOverride", "bool"},
    FieldDef{"ForceTypeOverride", "bool"},
}};

// CParticleNodeSpatialQuery (12 fields)
constexpr std::array<FieldDef, 12> kFields_CParticleNodeSpatialQuery{{
    FieldDef{"CustomName", "string_localized"},
    FieldDef{"Description", "string_localized"},
    FieldDef{"Active", "bool"},
    FieldDef{"ExecStage", "uint"},
    FieldDef{"ExecFrequency", "uint"},
    FieldDef{"InputPins", "link[]"},
    FieldDef{"OutputPins", "link[]"},
    FieldDef{"WorkspacePosition", "int2"},
    FieldDef{"WorkspaceRollupState", "int"},
    FieldDef{"QueryType", "int"},
    FieldDef{"PayloadName", "string"},
    FieldDef{"PayloadType", "int"},
}};

// CParticleNodeSplitter (11 fields)
constexpr std::array<FieldDef, 11> kFields_CParticleNodeSplitter{{
    FieldDef{"CustomName", "string_localized"},
    FieldDef{"Description", "string_localized"},
    FieldDef{"Active", "bool"},
    FieldDef{"ExecStage", "uint"},
    FieldDef{"ExecFrequency", "uint"},
    FieldDef{"InputPins", "link[]"},
    FieldDef{"OutputPins", "link[]"},
    FieldDef{"WorkspacePosition", "int2"},
    FieldDef{"WorkspaceRollupState", "int"},
    FieldDef{"Dimension", "uint"},
    FieldDef{"Mode", "int"},
}};

// CParticleNodeStaticTest (5 fields)
constexpr std::array<FieldDef, 5> kFields_CParticleNodeStaticTest{{
    FieldDef{"Test", "uint"},
    FieldDef{"CompareOp", "uint"},
    FieldDef{"CompareOp_", "uint"},
    FieldDef{"TestExecStage", "uint"},
    FieldDef{"TestExecFrequency", "uint"},
}};

// CParticleNodeStaticTypeSwitch (10 fields)
constexpr std::array<FieldDef, 10> kFields_CParticleNodeStaticTypeSwitch{{
    FieldDef{"CustomName", "string_localized"},
    FieldDef{"Description", "string_localized"},
    FieldDef{"Active", "bool"},
    FieldDef{"ExecStage", "uint"},
    FieldDef{"ExecFrequency", "uint"},
    FieldDef{"InputPins", "link[]"},
    FieldDef{"OutputPins", "link[]"},
    FieldDef{"WorkspacePosition", "int2"},
    FieldDef{"WorkspaceRollupState", "int"},
    FieldDef{"TypeEqualTo", "int"},
}};

// CParticleNodeStaticVersionSwitch (10 fields)
constexpr std::array<FieldDef, 10> kFields_CParticleNodeStaticVersionSwitch{{
    FieldDef{"CustomName", "string_localized"},
    FieldDef{"Description", "string_localized"},
    FieldDef{"Active", "bool"},
    FieldDef{"ExecStage", "uint"},
    FieldDef{"ExecFrequency", "uint"},
    FieldDef{"InputPins", "link[]"},
    FieldDef{"OutputPins", "link[]"},
    FieldDef{"WorkspacePosition", "int2"},
    FieldDef{"WorkspaceRollupState", "int"},
    FieldDef{"Versions", "string[]"},
}};

// CParticleNodeTemplate (16 fields)
constexpr std::array<FieldDef, 16> kFields_CParticleNodeTemplate{{
    FieldDef{"CustomName", "string_localized"},
    FieldDef{"Description", "string_localized"},
    FieldDef{"Active", "bool"},
    FieldDef{"ExecStage", "uint"},
    FieldDef{"ExecFrequency", "uint"},
    FieldDef{"InputPins", "link[]"},
    FieldDef{"OutputPins", "link[]"},
    FieldDef{"WorkspacePosition", "int2"},
    FieldDef{"WorkspaceRollupState", "int"},
    FieldDef{"AutoEntrypoint", "bool"},
    FieldDef{"SubGraphFilePath", "string"},
    FieldDef{"SubGraphName", "string_unicode"},
    FieldDef{"PreferredSimLocation", "int"},
    FieldDef{"Determinism", "int"},
    FieldDef{"RandomSeedModifier", "int"},
    FieldDef{"NodeGraph", "link"},
}};

// CParticleNodeTemplateExport (72 fields)
constexpr std::array<FieldDef, 72> kFields_CParticleNodeTemplateExport{{
    FieldDef{"CustomName", "string_localized"},
    FieldDef{"Description", "string_localized"},
    FieldDef{"Active", "bool"},
    FieldDef{"ExecStage", "uint"},
    FieldDef{"ExecFrequency", "uint"},
    FieldDef{"InputPins", "link[]"},
    FieldDef{"OutputPins", "link[]"},
    FieldDef{"WorkspacePosition", "int2"},
    FieldDef{"WorkspaceRollupState", "int"},
    FieldDef{"ExportedName", "string"},
    FieldDef{"ExportedType", "int"},
    FieldDef{"Semantic", "int"},
    FieldDef{"Type", "int"},
    FieldDef{"InputType", "int"},
    FieldDef{"Order", "int"},
    FieldDef{"VisibleByDefault", "bool"},
    FieldDef{"TransformSpace", "int"},
    FieldDef{"TransformMode", "int"},
    FieldDef{"CategoryName", "string_localized"},
    FieldDef{"UseDropDown", "bool"},
    FieldDef{"HasMin", "bool"},
    FieldDef{"HasMax", "bool"},
    FieldDef{"UseSlider", "bool"},
    FieldDef{"EnumList", "string[]"},
    FieldDef{"PassthroughInput", "string"},
    FieldDef{"DefaultValueF1", "float"},
    FieldDef{"DefaultValueF2", "float2"},
    FieldDef{"DefaultValueF3", "float3"},
    FieldDef{"DefaultValueF3C", "float3"},
    FieldDef{"DefaultValueF3D", "float3"},
    FieldDef{"DefaultValueF4", "float4"},
    FieldDef{"DefaultValueF4C", "float4"},
    FieldDef{"DefaultValueI1", "int"},
    FieldDef{"DefaultValueI2", "int2"},
    FieldDef{"DefaultValueI3", "int3"},
    FieldDef{"DefaultValueI3D", "int3"},
    FieldDef{"DefaultValueI4", "int4"},
    FieldDef{"DefaultValueB1", "bool"},
    FieldDef{"DefaultValueB2", "bool2"},
    FieldDef{"DefaultValueB3", "bool3"},
    FieldDef{"DefaultValueB4", "bool4"},
    FieldDef{"DefaultValueO", "float3"},
    FieldDef{"MinValueF1", "float"},
    FieldDef{"MinValueF2", "float2"},
    FieldDef{"MinValueF3", "float3"},
    FieldDef{"MinValueF3D", "float3"},
    FieldDef{"MinValueF4", "float4"},
    FieldDef{"MinValueI1", "int"},
    FieldDef{"MinValueI2", "int2"},
    FieldDef{"MinValueI3", "int3"},
    FieldDef{"MinValueI3D", "int3"},
    FieldDef{"MinValueI4", "int4"},
    FieldDef{"MaxValueF1", "float"},
    FieldDef{"MaxValueF2", "float2"},
    FieldDef{"MaxValueF3", "float3"},
    FieldDef{"MaxValueF3D", "float3"},
    FieldDef{"MaxValueF4", "float4"},
    FieldDef{"MaxValueI1", "int"},
    FieldDef{"MaxValueI2", "int2"},
    FieldDef{"MaxValueI3", "int3"},
    FieldDef{"MaxValueI3D", "int3"},
    FieldDef{"MaxValueI4", "int4"},
    FieldDef{"DefaultValueData", "string"},
    FieldDef{"PinRules", "int"},
    FieldDef{"BaseVisibility", "int"},
    FieldDef{"RuleResult", "int"},
    FieldDef{"DependentProperty", "string"},
    FieldDef{"RuleFunction", "int"},
    FieldDef{"RuleValue", "string"},
    FieldDef{"DependentProperty2", "string"},
    FieldDef{"RuleFunction2", "int"},
    FieldDef{"RuleValue2", "string"},
}};

// CParticleNodeTransform (13 fields)
constexpr std::array<FieldDef, 13> kFields_CParticleNodeTransform{{
    FieldDef{"CustomName", "string_localized"},
    FieldDef{"Description", "string_localized"},
    FieldDef{"Active", "bool"},
    FieldDef{"ExecStage", "uint"},
    FieldDef{"ExecFrequency", "uint"},
    FieldDef{"InputPins", "link[]"},
    FieldDef{"OutputPins", "link[]"},
    FieldDef{"WorkspacePosition", "int2"},
    FieldDef{"WorkspaceRollupState", "int"},
    FieldDef{"InputSpace", "uint"},
    FieldDef{"OutputSpace", "uint"},
    FieldDef{"TransformMode", "uint"},
    FieldDef{"ApplyScale", "bool"},
}};

// CParticleNodeTransformOrientation (2 fields)
constexpr std::array<FieldDef, 2> kFields_CParticleNodeTransformOrientation{{
    FieldDef{"InputSpace", "uint"},
    FieldDef{"OutputSpace", "uint"},
}};

// CParticleNodeTypeCast (10 fields)
constexpr std::array<FieldDef, 10> kFields_CParticleNodeTypeCast{{
    FieldDef{"CustomName", "string_localized"},
    FieldDef{"Description", "string_localized"},
    FieldDef{"Active", "bool"},
    FieldDef{"ExecStage", "uint"},
    FieldDef{"ExecFrequency", "uint"},
    FieldDef{"InputPins", "link[]"},
    FieldDef{"OutputPins", "link[]"},
    FieldDef{"WorkspacePosition", "int2"},
    FieldDef{"WorkspaceRollupState", "int"},
    FieldDef{"TargetType", "int"},
}};

// CParticleRendererFeature (3 fields)
constexpr std::array<FieldDef, 3> kFields_CParticleRendererFeature{{
    FieldDef{"FeatureName", "string"},
    FieldDef{"Feature", "link"},
    FieldDef{"Properties", "link[]"},
}};

// CParticleRendererFeatureDesc (3 fields)
constexpr std::array<FieldDef, 3> kFields_CParticleRendererFeatureDesc{{
    FieldDef{"RendererInterfacePath", "string"},
    FieldDef{"RendererFeatureName", "string"},
    FieldDef{"Mandatory", "bool"},
}};

// CParticleRendererFeatureSet (1 fields)
constexpr std::array<FieldDef, 1> kFields_CParticleRendererFeatureSet{{
    FieldDef{"RendererFeatures", "link[]"},
}};

// CParticleTimeline (3 fields)
constexpr std::array<FieldDef, 3> kFields_CParticleTimeline{{
    FieldDef{"Tracks", "link[]"},
    FieldDef{"WorkspacePosition", "float"},
    FieldDef{"WorkspaceZoom", "int"},
}};

// CParticleTimelineTrack (8 fields)
constexpr std::array<FieldDef, 8> kFields_CParticleTimelineTrack{{
    FieldDef{"CustomName", "string_unicode"},
    FieldDef{"Description", "string_unicode"},
    FieldDef{"CategoryName", "string_unicode"},
    FieldDef{"Enabled", "bool"},
    FieldDef{"OverrideColor", "bool"},
    FieldDef{"EditorColor", "uint3"},
    FieldDef{"EventStream", "link"},
    FieldDef{"Collapsed", "bool"},
}};

// CProjectSettings (6 fields)
constexpr std::array<FieldDef, 6> kFields_CProjectSettings{{
    FieldDef{"General", "link"},
    FieldDef{"Scene", "link"},
    FieldDef{"LOD", "link"},
    FieldDef{"Documentation", "link"},
    FieldDef{"Assets", "link"},
    FieldDef{"Baking", "link"},
}};

// CProjectSettingsAssets (14 fields)
constexpr std::array<FieldDef, 14> kFields_CProjectSettingsAssets{{
    FieldDef{"IgnoredPaths", "string"},
    FieldDef{"EffectExtensions", "string[]"},
    FieldDef{"MeshExtensions", "string[]"},
    FieldDef{"ImageExtensions", "string[]"},
    FieldDef{"ImageAtlasExtensions", "string[]"},
    FieldDef{"FontExtensions", "string[]"},
    FieldDef{"VectorFieldExtensions", "string[]"},
    FieldDef{"SoundExtensions", "string[]"},
    FieldDef{"SimCacheExtensions", "string[]"},
    FieldDef{"FeatureSetExtensions", "string[]"},
    FieldDef{"VertexShaderExtensions", "string[]"},
    FieldDef{"FragmentShaderExtensions", "string[]"},
    FieldDef{"RendererInterfaceExtensions", "string[]"},
    FieldDef{"VideoExtensions", "string[]"},
}};

// CProjectSettingsBaking (2 fields)
constexpr std::array<FieldDef, 2> kFields_CProjectSettingsBaking{{
    FieldDef{"PlatformSettingsList", "string[]"},
    FieldDef{"BuildVersions", "string[]"},
}};

// CProjectSettingsDocumentation (2 fields)
constexpr std::array<FieldDef, 2> kFields_CProjectSettingsDocumentation{{
    FieldDef{"StyleSheetPath", "string"},
    FieldDef{"InlineStyleSheet", "bool"},
}};

// CProjectSettingsGeneral (11 fields)
constexpr std::array<FieldDef, 11> kFields_CProjectSettingsGeneral{{
    FieldDef{"ProjectName", "string_unicode"},
    FieldDef{"ProjectDescription", "string_unicode"},
    FieldDef{"RootDir", "string"},
    FieldDef{"TemplatesDir", "string"},
    FieldDef{"AnimationTracksDir", "string"},
    FieldDef{"ThumbnailsDir", "string"},
    FieldDef{"LibraryDir", "string"},
    FieldDef{"RuntimeConfigsDir", "string"},
    FieldDef{"DocumentationDir", "string"},
    FieldDef{"EditorCacheDir", "string"},
    FieldDef{"ExternalResourcesPathList", "string[]"},
}};

// CProjectSettingsLOD (3 fields)
constexpr std::array<FieldDef, 3> kFields_CProjectSettingsLOD{{
    FieldDef{"MinDistance", "float"},
    FieldDef{"MaxDistance", "float"},
    FieldDef{"MinMinDistance", "float"},
}};

// CProjectSettingsScene (17 fields)
constexpr std::array<FieldDef, 17> kFields_CProjectSettingsScene{{
    FieldDef{"CoordinateFrame", "int"},
    FieldDef{"CoordinateFrameAxisX", "int"},
    FieldDef{"CoordinateFrameAxisY", "int"},
    FieldDef{"CoordinateFrameAxisZ", "int"},
    FieldDef{"DistanceUnits", "int"},
    FieldDef{"Enable_Scene_SampleWindField", "bool"},
    FieldDef{"DefaultRestitution", "float"},
    FieldDef{"DefaultRestitutionCombineMode", "int"},
    FieldDef{"DefaultFriction", "float"},
    FieldDef{"DefaultFrictionCombineMode", "int"},
    FieldDef{"WindScale", "float"},
    FieldDef{"SurfaceTypeList", "string[]"},
    FieldDef{"CollisionFilterList", "string[]"},
    FieldDef{"AudioSampleCount", "uint"},
    FieldDef{"AudioSpectrumMinFreq", "uint"},
    FieldDef{"AudioSpectrumMaxFreq", "uint"},
    FieldDef{"AudioSpectrumHasLogScale", "bool"},
}};

// CSamplerCurve (8 fields)
constexpr std::array<FieldDef, 8> kFields_CSamplerCurve{{
    FieldDef{"BindingSemantic", "string"},
    FieldDef{"ValueType", "uint"},
    FieldDef{"Interpolator", "uint"},
    FieldDef{"Times", "float[]"},
    FieldDef{"FloatValues", "float[]"},
    FieldDef{"FloatTangents", "float[]"},
    FieldDef{"MinLimits", "float4"},
    FieldDef{"MaxLimits", "float4"},
}};

// CSkeletonAnimation (8 fields)
constexpr std::array<FieldDef, 8> kFields_CSkeletonAnimation{{
    FieldDef{"BoneStreams", "link[]"},
    FieldDef{"LengthInSeconds", "float"},
    FieldDef{"PlaybackSpeed", "float"},
    FieldDef{"AnimationName", "string"},
    FieldDef{"CoordinateFrame", "uint"},
    FieldDef{"CoordinateFrameAxisX", "uint"},
    FieldDef{"CoordinateFrameAxisY", "uint"},
    FieldDef{"CoordinateFrameAxisZ", "uint"},
}};

// CSkeletonAnimationBone (2 fields)
constexpr std::array<FieldDef, 2> kFields_CSkeletonAnimationBone{{
    FieldDef{"TargetBone", "string"},
    FieldDef{"Channels", "link[]"},
}};

constexpr std::array<HandlerDef, 116> kHandlerDefs{{
    HandlerDef{"CAnimationClip", std::span<const FieldDef>(kFields_CAnimationClip.data(), kFields_CAnimationClip.size())},
    HandlerDef{"CAnimationTrack", std::span<const FieldDef>(kFields_CAnimationTrack.data(), kFields_CAnimationTrack.size())},
    HandlerDef{"CBaseSettings", std::span<const FieldDef>(kFields_CBaseSettings.data(), kFields_CBaseSettings.size())},
    HandlerDef{"CCompilerBlobCache", std::span<const FieldDef>(kFields_CCompilerBlobCache.data(), kFields_CCompilerBlobCache.size())},
    HandlerDef{"CCompilerBlobCacheEntryPoint", std::span<const FieldDef>(kFields_CCompilerBlobCacheEntryPoint.data(), kFields_CCompilerBlobCacheEntryPoint.size())},
    HandlerDef{"CCompilerBlobCacheExternal", std::span<const FieldDef>(kFields_CCompilerBlobCacheExternal.data(), kFields_CCompilerBlobCacheExternal.size())},
    HandlerDef{"CCompilerBlobCacheFunctionArg", std::span<const FieldDef>(kFields_CCompilerBlobCacheFunctionArg.data(), kFields_CCompilerBlobCacheFunctionArg.size())},
    HandlerDef{"CCompilerBlobCacheFunctionDef", std::span<const FieldDef>(kFields_CCompilerBlobCacheFunctionDef.data(), kFields_CCompilerBlobCacheFunctionDef.size())},
    HandlerDef{"CEditorAssetEffect", std::span<const FieldDef>(kFields_CEditorAssetEffect.data(), kFields_CEditorAssetEffect.size())},
    HandlerDef{"CEngineRendererInterface", std::span<const FieldDef>(kFields_CEngineRendererInterface.data(), kFields_CEngineRendererInterface.size())},
    HandlerDef{"CLayerCompileCache", std::span<const FieldDef>(kFields_CLayerCompileCache.data(), kFields_CLayerCompileCache.size())},
    HandlerDef{"CLayerCompileCacheAttrib", std::span<const FieldDef>(kFields_CLayerCompileCacheAttrib.data(), kFields_CLayerCompileCacheAttrib.size())},
    HandlerDef{"CLayerCompileCacheAttribSampler", std::span<const FieldDef>(kFields_CLayerCompileCacheAttribSampler.data(), kFields_CLayerCompileCacheAttribSampler.size())},
    HandlerDef{"CLayerCompileCacheEvent", std::span<const FieldDef>(kFields_CLayerCompileCacheEvent.data(), kFields_CLayerCompileCacheEvent.size())},
    HandlerDef{"CLayerCompileCacheEventPayload", std::span<const FieldDef>(kFields_CLayerCompileCacheEventPayload.data(), kFields_CLayerCompileCacheEventPayload.size())},
    HandlerDef{"CLayerCompileCacheField", std::span<const FieldDef>(kFields_CLayerCompileCacheField.data(), kFields_CLayerCompileCacheField.size())},
    HandlerDef{"CLayerCompileCacheRenderer", std::span<const FieldDef>(kFields_CLayerCompileCacheRenderer.data(), kFields_CLayerCompileCacheRenderer.size())},
    HandlerDef{"CLayerCompileCacheRendererParticleInput", std::span<const FieldDef>(kFields_CLayerCompileCacheRendererParticleInput.data(), kFields_CLayerCompileCacheRendererParticleInput.size())},
    HandlerDef{"CLayerCompileCacheRendererProperty", std::span<const FieldDef>(kFields_CLayerCompileCacheRendererProperty.data(), kFields_CLayerCompileCacheRendererProperty.size())},
    HandlerDef{"CLayerCompileCacheSampler", std::span<const FieldDef>(kFields_CLayerCompileCacheSampler.data(), kFields_CLayerCompileCacheSampler.size())},
    HandlerDef{"CLayerCompileCacheSpatialLayer", std::span<const FieldDef>(kFields_CLayerCompileCacheSpatialLayer.data(), kFields_CLayerCompileCacheSpatialLayer.size())},
    HandlerDef{"CLayerCompileCacheSpatialLayerPayload", std::span<const FieldDef>(kFields_CLayerCompileCacheSpatialLayerPayload.data(), kFields_CLayerCompileCacheSpatialLayerPayload.size())},
    HandlerDef{"CLayerGraphCompileCache", std::span<const FieldDef>(kFields_CLayerGraphCompileCache.data(), kFields_CLayerGraphCompileCache.size())},
    HandlerDef{"CLayerGraphCompileCache_BroadSlot", std::span<const FieldDef>(kFields_CLayerGraphCompileCache_BroadSlot.data(), kFields_CLayerGraphCompileCache_BroadSlot.size())},
    HandlerDef{"CLayerGraphCompileCache_EntrySlot", std::span<const FieldDef>(kFields_CLayerGraphCompileCache_EntrySlot.data(), kFields_CLayerGraphCompileCache_EntrySlot.size())},
    HandlerDef{"CLayerGraphCompileCache_EventSlot", std::span<const FieldDef>(kFields_CLayerGraphCompileCache_EventSlot.data(), kFields_CLayerGraphCompileCache_EventSlot.size())},
    HandlerDef{"CLayerGraphCompileCache_LayerSlot", std::span<const FieldDef>(kFields_CLayerGraphCompileCache_LayerSlot.data(), kFields_CLayerGraphCompileCache_LayerSlot.size())},
    HandlerDef{"CParticleAttributeDeclaration", std::span<const FieldDef>(kFields_CParticleAttributeDeclaration.data(), kFields_CParticleAttributeDeclaration.size())},
    HandlerDef{"CParticleAttributeList", std::span<const FieldDef>(kFields_CParticleAttributeList.data(), kFields_CParticleAttributeList.size())},
    HandlerDef{"CParticleAttributeSamplerDeclaration", std::span<const FieldDef>(kFields_CParticleAttributeSamplerDeclaration.data(), kFields_CParticleAttributeSamplerDeclaration.size())},
    HandlerDef{"CParticleEffect", std::span<const FieldDef>(kFields_CParticleEffect.data(), kFields_CParticleEffect.size())},
    HandlerDef{"CParticleNode", std::span<const FieldDef>(kFields_CParticleNode.data(), kFields_CParticleNode.size())},
    HandlerDef{"CParticleNodeAnnotation", std::span<const FieldDef>(kFields_CParticleNodeAnnotation.data(), kFields_CParticleNodeAnnotation.size())},
    HandlerDef{"CParticleNodeArithmetic", std::span<const FieldDef>(kFields_CParticleNodeArithmetic.data(), kFields_CParticleNodeArithmetic.size())},
    HandlerDef{"CParticleNodeAssign", std::span<const FieldDef>(kFields_CParticleNodeAssign.data(), kFields_CParticleNodeAssign.size())},
    HandlerDef{"CParticleNodeCompare", std::span<const FieldDef>(kFields_CParticleNodeCompare.data(), kFields_CParticleNodeCompare.size())},
    HandlerDef{"CParticleNodeConstant", std::span<const FieldDef>(kFields_CParticleNodeConstant.data(), kFields_CParticleNodeConstant.size())},
    HandlerDef{"CParticleNodeConstructor", std::span<const FieldDef>(kFields_CParticleNodeConstructor.data(), kFields_CParticleNodeConstructor.size())},
    HandlerDef{"CParticleNodeDebugCheck", std::span<const FieldDef>(kFields_CParticleNodeDebugCheck.data(), kFields_CParticleNodeDebugCheck.size())},
    HandlerDef{"CParticleNodeDiscretizationPoint", std::span<const FieldDef>(kFields_CParticleNodeDiscretizationPoint.data(), kFields_CParticleNodeDiscretizationPoint.size())},
    HandlerDef{"CParticleNodeEvaluateAtSpawn", std::span<const FieldDef>(kFields_CParticleNodeEvaluateAtSpawn.data(), kFields_CParticleNodeEvaluateAtSpawn.size())},
    HandlerDef{"CParticleNodeEventGenerator", std::span<const FieldDef>(kFields_CParticleNodeEventGenerator.data(), kFields_CParticleNodeEventGenerator.size())},
    HandlerDef{"CParticleNodeEventParent", std::span<const FieldDef>(kFields_CParticleNodeEventParent.data(), kFields_CParticleNodeEventParent.size())},
    HandlerDef{"CParticleNodeEventPayloadAppend", std::span<const FieldDef>(kFields_CParticleNodeEventPayloadAppend.data(), kFields_CParticleNodeEventPayloadAppend.size())},
    HandlerDef{"CParticleNodeEventPayloadAppendBase", std::span<const FieldDef>(kFields_CParticleNodeEventPayloadAppendBase.data(), kFields_CParticleNodeEventPayloadAppendBase.size())},
    HandlerDef{"CParticleNodeEventPayloadAppendInterp", std::span<const FieldDef>(kFields_CParticleNodeEventPayloadAppendInterp.data(), kFields_CParticleNodeEventPayloadAppendInterp.size())},
    HandlerDef{"CParticleNodeEventPayloadBase", std::span<const FieldDef>(kFields_CParticleNodeEventPayloadBase.data(), kFields_CParticleNodeEventPayloadBase.size())},
    HandlerDef{"CParticleNodeEventPayloadClear", std::span<const FieldDef>(kFields_CParticleNodeEventPayloadClear.data(), kFields_CParticleNodeEventPayloadClear.size())},
    HandlerDef{"CParticleNodeEventPayloadCopy", std::span<const FieldDef>(kFields_CParticleNodeEventPayloadCopy.data(), kFields_CParticleNodeEventPayloadCopy.size())},
    HandlerDef{"CParticleNodeEventPayloadExtract", std::span<const FieldDef>(kFields_CParticleNodeEventPayloadExtract.data(), kFields_CParticleNodeEventPayloadExtract.size())},
    HandlerDef{"CParticleNodeEventPayloadExtractBase", std::span<const FieldDef>(kFields_CParticleNodeEventPayloadExtractBase.data(), kFields_CParticleNodeEventPayloadExtractBase.size())},
    HandlerDef{"CParticleNodeEventPayloadExtractInterp", std::span<const FieldDef>(kFields_CParticleNodeEventPayloadExtractInterp.data(), kFields_CParticleNodeEventPayloadExtractInterp.size())},
    HandlerDef{"CParticleNodeEventStart", std::span<const FieldDef>(kFields_CParticleNodeEventStart.data(), kFields_CParticleNodeEventStart.size())},
    HandlerDef{"CParticleNodeEventTrigger", std::span<const FieldDef>(kFields_CParticleNodeEventTrigger.data(), kFields_CParticleNodeEventTrigger.size())},
    HandlerDef{"CParticleNodeGraph", std::span<const FieldDef>(kFields_CParticleNodeGraph.data(), kFields_CParticleNodeGraph.size())},
    HandlerDef{"CParticleNodeIf", std::span<const FieldDef>(kFields_CParticleNodeIf.data(), kFields_CParticleNodeIf.size())},
    HandlerDef{"CParticleNodeIntegrate", std::span<const FieldDef>(kFields_CParticleNodeIntegrate.data(), kFields_CParticleNodeIntegrate.size())},
    HandlerDef{"CParticleNodeLayer", std::span<const FieldDef>(kFields_CParticleNodeLayer.data(), kFields_CParticleNodeLayer.size())},
    HandlerDef{"CParticleNodeMathFunction1", std::span<const FieldDef>(kFields_CParticleNodeMathFunction1.data(), kFields_CParticleNodeMathFunction1.size())},
    HandlerDef{"CParticleNodeMathFunction2", std::span<const FieldDef>(kFields_CParticleNodeMathFunction2.data(), kFields_CParticleNodeMathFunction2.size())},
    HandlerDef{"CParticleNodeMathFunction3", std::span<const FieldDef>(kFields_CParticleNodeMathFunction3.data(), kFields_CParticleNodeMathFunction3.size())},
    HandlerDef{"CParticleNodeMathWaveform", std::span<const FieldDef>(kFields_CParticleNodeMathWaveform.data(), kFields_CParticleNodeMathWaveform.size())},
    HandlerDef{"CParticleNodePartialDerivative", std::span<const FieldDef>(kFields_CParticleNodePartialDerivative.data(), kFields_CParticleNodePartialDerivative.size())},
    HandlerDef{"CParticleNodePassThrough", std::span<const FieldDef>(kFields_CParticleNodePassThrough.data(), kFields_CParticleNodePassThrough.size())},
    HandlerDef{"CParticleNodePinAbstract", std::span<const FieldDef>(kFields_CParticleNodePinAbstract.data(), kFields_CParticleNodePinAbstract.size())},
    HandlerDef{"CParticleNodePinIn", std::span<const FieldDef>(kFields_CParticleNodePinIn.data(), kFields_CParticleNodePinIn.size())},
    HandlerDef{"CParticleNodePinOut", std::span<const FieldDef>(kFields_CParticleNodePinOut.data(), kFields_CParticleNodePinOut.size())},
    HandlerDef{"CParticleNodeReinterpret", std::span<const FieldDef>(kFields_CParticleNodeReinterpret.data(), kFields_CParticleNodeReinterpret.size())},
    HandlerDef{"CParticleNodeRendererBase", std::span<const FieldDef>(kFields_CParticleNodeRendererBase.data(), kFields_CParticleNodeRendererBase.size())},
    HandlerDef{"CParticleNodeRendererBillboard", std::span<const FieldDef>(kFields_CParticleNodeRendererBillboard.data(), kFields_CParticleNodeRendererBillboard.size())},
    HandlerDef{"CParticleNodeRendererLight", std::span<const FieldDef>(kFields_CParticleNodeRendererLight.data(), kFields_CParticleNodeRendererLight.size())},
    HandlerDef{"CParticleNodeRendererMesh", std::span<const FieldDef>(kFields_CParticleNodeRendererMesh.data(), kFields_CParticleNodeRendererMesh.size())},
    HandlerDef{"CParticleNodeRendererRibbon", std::span<const FieldDef>(kFields_CParticleNodeRendererRibbon.data(), kFields_CParticleNodeRendererRibbon.size())},
    HandlerDef{"CParticleNodeRendererSound", std::span<const FieldDef>(kFields_CParticleNodeRendererSound.data(), kFields_CParticleNodeRendererSound.size())},
    HandlerDef{"CParticleNodeSamplerData", std::span<const FieldDef>(kFields_CParticleNodeSamplerData.data(), kFields_CParticleNodeSamplerData.size())},
    HandlerDef{"CParticleNodeSamplerData_AnimTrack", std::span<const FieldDef>(kFields_CParticleNodeSamplerData_AnimTrack.data(), kFields_CParticleNodeSamplerData_AnimTrack.size())},
    HandlerDef{"CParticleNodeSamplerData_Audio", std::span<const FieldDef>(kFields_CParticleNodeSamplerData_Audio.data(), kFields_CParticleNodeSamplerData_Audio.size())},
    HandlerDef{"CParticleNodeSamplerData_Curve", std::span<const FieldDef>(kFields_CParticleNodeSamplerData_Curve.data(), kFields_CParticleNodeSamplerData_Curve.size())},
    HandlerDef{"CParticleNodeSamplerData_DoubleCurve", std::span<const FieldDef>(kFields_CParticleNodeSamplerData_DoubleCurve.data(), kFields_CParticleNodeSamplerData_DoubleCurve.size())},
    HandlerDef{"CParticleNodeSamplerData_EventStream", std::span<const FieldDef>(kFields_CParticleNodeSamplerData_EventStream.data(), kFields_CParticleNodeSamplerData_EventStream.size())},
    HandlerDef{"CParticleNodeSamplerData_EventStream_Payload", std::span<const FieldDef>(kFields_CParticleNodeSamplerData_EventStream_Payload.data(), kFields_CParticleNodeSamplerData_EventStream_Payload.size())},
    HandlerDef{"CParticleNodeSamplerData_Shape", std::span<const FieldDef>(kFields_CParticleNodeSamplerData_Shape.data(), kFields_CParticleNodeSamplerData_Shape.size())},
    HandlerDef{"CParticleNodeSamplerData_Text", std::span<const FieldDef>(kFields_CParticleNodeSamplerData_Text.data(), kFields_CParticleNodeSamplerData_Text.size())},
    HandlerDef{"CParticleNodeSamplerData_Texture", std::span<const FieldDef>(kFields_CParticleNodeSamplerData_Texture.data(), kFields_CParticleNodeSamplerData_Texture.size())},
    HandlerDef{"CParticleNodeSamplerData_Turbulence", std::span<const FieldDef>(kFields_CParticleNodeSamplerData_Turbulence.data(), kFields_CParticleNodeSamplerData_Turbulence.size())},
    HandlerDef{"CParticleNodeScript", std::span<const FieldDef>(kFields_CParticleNodeScript.data(), kFields_CParticleNodeScript.size())},
    HandlerDef{"CParticleNodeSetLife", std::span<const FieldDef>(kFields_CParticleNodeSetLife.data(), kFields_CParticleNodeSetLife.size())},
    HandlerDef{"CParticleNodeSpatialInsert", std::span<const FieldDef>(kFields_CParticleNodeSpatialInsert.data(), kFields_CParticleNodeSpatialInsert.size())},
    HandlerDef{"CParticleNodeSpatialLayer", std::span<const FieldDef>(kFields_CParticleNodeSpatialLayer.data(), kFields_CParticleNodeSpatialLayer.size())},
    HandlerDef{"CParticleNodeSpatialLayerStorage", std::span<const FieldDef>(kFields_CParticleNodeSpatialLayerStorage.data(), kFields_CParticleNodeSpatialLayerStorage.size())},
    HandlerDef{"CParticleNodeSpatialPayloadAppend", std::span<const FieldDef>(kFields_CParticleNodeSpatialPayloadAppend.data(), kFields_CParticleNodeSpatialPayloadAppend.size())},
    HandlerDef{"CParticleNodeSpatialQuery", std::span<const FieldDef>(kFields_CParticleNodeSpatialQuery.data(), kFields_CParticleNodeSpatialQuery.size())},
    HandlerDef{"CParticleNodeSplitter", std::span<const FieldDef>(kFields_CParticleNodeSplitter.data(), kFields_CParticleNodeSplitter.size())},
    HandlerDef{"CParticleNodeStaticTest", std::span<const FieldDef>(kFields_CParticleNodeStaticTest.data(), kFields_CParticleNodeStaticTest.size())},
    HandlerDef{"CParticleNodeStaticTypeSwitch", std::span<const FieldDef>(kFields_CParticleNodeStaticTypeSwitch.data(), kFields_CParticleNodeStaticTypeSwitch.size())},
    HandlerDef{"CParticleNodeStaticVersionSwitch", std::span<const FieldDef>(kFields_CParticleNodeStaticVersionSwitch.data(), kFields_CParticleNodeStaticVersionSwitch.size())},
    HandlerDef{"CParticleNodeTemplate", std::span<const FieldDef>(kFields_CParticleNodeTemplate.data(), kFields_CParticleNodeTemplate.size())},
    HandlerDef{"CParticleNodeTemplateExport", std::span<const FieldDef>(kFields_CParticleNodeTemplateExport.data(), kFields_CParticleNodeTemplateExport.size())},
    HandlerDef{"CParticleNodeTransform", std::span<const FieldDef>(kFields_CParticleNodeTransform.data(), kFields_CParticleNodeTransform.size())},
    HandlerDef{"CParticleNodeTransformOrientation", std::span<const FieldDef>(kFields_CParticleNodeTransformOrientation.data(), kFields_CParticleNodeTransformOrientation.size())},
    HandlerDef{"CParticleNodeTypeCast", std::span<const FieldDef>(kFields_CParticleNodeTypeCast.data(), kFields_CParticleNodeTypeCast.size())},
    HandlerDef{"CParticleRendererFeature", std::span<const FieldDef>(kFields_CParticleRendererFeature.data(), kFields_CParticleRendererFeature.size())},
    HandlerDef{"CParticleRendererFeatureDesc", std::span<const FieldDef>(kFields_CParticleRendererFeatureDesc.data(), kFields_CParticleRendererFeatureDesc.size())},
    HandlerDef{"CParticleRendererFeatureSet", std::span<const FieldDef>(kFields_CParticleRendererFeatureSet.data(), kFields_CParticleRendererFeatureSet.size())},
    HandlerDef{"CParticleTimeline", std::span<const FieldDef>(kFields_CParticleTimeline.data(), kFields_CParticleTimeline.size())},
    HandlerDef{"CParticleTimelineTrack", std::span<const FieldDef>(kFields_CParticleTimelineTrack.data(), kFields_CParticleTimelineTrack.size())},
    HandlerDef{"CProjectSettings", std::span<const FieldDef>(kFields_CProjectSettings.data(), kFields_CProjectSettings.size())},
    HandlerDef{"CProjectSettingsAssets", std::span<const FieldDef>(kFields_CProjectSettingsAssets.data(), kFields_CProjectSettingsAssets.size())},
    HandlerDef{"CProjectSettingsBaking", std::span<const FieldDef>(kFields_CProjectSettingsBaking.data(), kFields_CProjectSettingsBaking.size())},
    HandlerDef{"CProjectSettingsDocumentation", std::span<const FieldDef>(kFields_CProjectSettingsDocumentation.data(), kFields_CProjectSettingsDocumentation.size())},
    HandlerDef{"CProjectSettingsGeneral", std::span<const FieldDef>(kFields_CProjectSettingsGeneral.data(), kFields_CProjectSettingsGeneral.size())},
    HandlerDef{"CProjectSettingsLOD", std::span<const FieldDef>(kFields_CProjectSettingsLOD.data(), kFields_CProjectSettingsLOD.size())},
    HandlerDef{"CProjectSettingsScene", std::span<const FieldDef>(kFields_CProjectSettingsScene.data(), kFields_CProjectSettingsScene.size())},
    HandlerDef{"CSamplerCurve", std::span<const FieldDef>(kFields_CSamplerCurve.data(), kFields_CSamplerCurve.size())},
    HandlerDef{"CSkeletonAnimation", std::span<const FieldDef>(kFields_CSkeletonAnimation.data(), kFields_CSkeletonAnimation.size())},
    HandlerDef{"CSkeletonAnimationBone", std::span<const FieldDef>(kFields_CSkeletonAnimationBone.data(), kFields_CSkeletonAnimationBone.size())},
}};

} // namespace

const HandlerDef* findHandlerDef(std::string_view handlerName) noexcept {
    const auto* first = kHandlerDefs.data();
    const auto* last = first + kHandlerDefs.size();
    const auto* it = std::lower_bound(
        first, last, handlerName,
        [](const HandlerDef& h, std::string_view name) noexcept { return h.name < name; });
    if (it == last || it->name != handlerName) {
        return nullptr;
    }
    return it;
}

std::size_t handlerDefCount() noexcept {
    return kHandlerDefs.size();
}

} // namespace whiteout::cornflakes
