// SPDX-License-Identifier: BSD-3-Clause
// Copyright (c) 2026 Fernando Sahmkow
//
// Hand-written supplement to `flakes.rs`. NOT autogenerated — the
// codegen never touches this file.
//
// Everything here fills a gap the Rust emitter leaves; the "Not yet
// bound" list at the bottom of `flakes.rs` is the authoritative
// inventory of what is still missing. Two categories are covered:
//
//   * Field-only value structs (`FrameStats`, `ShadowParams`,
//     `AssetsViewStats`) in method signatures. The emitter renders them
//     as plain Rust structs but declines them as parameter and return
//     shapes, so the round trip through the C handle is written here.
//     These call *generated* C symbols.
//
//   * Shapes the C generator declines too — `void*` window handles, math
//     types, vectors of bound structs. These call the hand-written C
//     symbols in `bindings/c/whiteout_flakes_shims.cpp`.
//
// Math crosses as flat arrays rather than through a `Vector3f` type of
// our own: callers already have a math library, and `[f32; 3]` converts
// into every one of them for free.

use crate::flakes::ffi;
use crate::flakes::{ActorView, AssetsView, AssetsViewStats, CameraPreset, DncView, SceneView};
use crate::flakes::{CameraView, FrameStats, PipelineView, SequenceInfo, ShadowParams, ShadowView};
use crate::support::{take_string, RawCString};

extern "C" {
    // Generated (whiteout_flakes.cpp), but absent from `flakes.rs`'s own
    // extern block because the emitter skipped the wrapping method.
    fn whiteout_flakes_FlakesPipelineView_FrameStats(
        self_: *const ffi::whiteout_FlakesPipelineView,
    ) -> *mut ffi::whiteout_FlakesFrameStats;
    fn whiteout_flakes_FlakesShadowView_Params(
        self_: *const ffi::whiteout_FlakesShadowView,
    ) -> *mut ffi::whiteout_FlakesShadowParams;
    fn whiteout_flakes_FlakesShadowView_SetParams(
        self_: *mut ffi::whiteout_FlakesShadowView,
        params: *mut ffi::whiteout_FlakesShadowParams,
    );
    fn whiteout_flakes_FlakesAssetsView_Stats(
        self_: *const ffi::whiteout_FlakesAssetsView,
    ) -> *mut ffi::whiteout_FlakesAssetsViewStats;

    // Hand-written (whiteout_flakes_shims.cpp).
    fn whiteout_flakes_FlakesSceneView_SetPE1BasePath(
        self_: *mut ffi::whiteout_FlakesSceneView,
        path: *const core::ffi::c_char,
    );
    fn whiteout_flakes_FlakesDncView_UnitMdlPath(
        self_: *const ffi::whiteout_FlakesDncView,
    ) -> RawCString;
    fn whiteout_flakes_FlakesPipelineView_CreateSwapChainTarget(
        self_: *mut ffi::whiteout_FlakesPipelineView,
        hwnd: usize,
        width: i32,
        height: i32,
    ) -> u32;
    fn whiteout_flakes_FlakesCameraView_GetTargetFlat(
        self_: *const ffi::whiteout_FlakesCameraView,
        out: *mut f32,
    );
    fn whiteout_flakes_FlakesCameraView_SetDirectPoseFlat(
        self_: *mut ffi::whiteout_FlakesCameraView,
        px: f32,
        py: f32,
        pz: f32,
        tx: f32,
        ty: f32,
        tz: f32,
        roll: f32,
    );
    fn whiteout_flakes_FlakesActorView_TransformFlat(
        self_: *const ffi::whiteout_FlakesActorView,
        out: *mut f32,
    );
    fn whiteout_flakes_FlakesActorView_SetTransformFlat(
        self_: *mut ffi::whiteout_FlakesActorView,
        m: *const f32,
    );
    fn whiteout_flakes_FlakesActorView_Sequences_count(
        self_: *const ffi::whiteout_FlakesActorView,
    ) -> usize;
    fn whiteout_flakes_FlakesActorView_Sequences_at(
        self_: *const ffi::whiteout_FlakesActorView,
        index: usize,
    ) -> *mut ffi::whiteout_FlakesSequenceInfo;
    fn whiteout_flakes_FlakesActorView_CameraPresets_count(
        self_: *const ffi::whiteout_FlakesActorView,
    ) -> usize;
    fn whiteout_flakes_FlakesActorView_CameraPresets_at(
        self_: *const ffi::whiteout_FlakesActorView,
        index: usize,
    ) -> *mut ffi::whiteout_FlakesCameraPreset;
}

// ── Value-struct round trips ──────────────────────────────────────────────
//
// The C ABI hands back a heap handle; we read the fields out and free it
// immediately, so the value the caller sees owns nothing.

/// # Safety
/// `h` must be a live handle this call takes ownership of.
unsafe fn frame_stats_from_raw(h: *mut ffi::whiteout_FlakesFrameStats) -> Option<FrameStats> {
    if h.is_null() {
        return None;
    }
    unsafe {
        let out = FrameStats {
            geosets: ffi::whiteout_flakes_FlakesFrameStats_get_geosets(h),
            textures: ffi::whiteout_flakes_FlakesFrameStats_get_textures(h),
            nodes: ffi::whiteout_flakes_FlakesFrameStats_get_nodes(h),
            particles: ffi::whiteout_flakes_FlakesFrameStats_get_particles(h),
            segments: ffi::whiteout_flakes_FlakesFrameStats_get_segments(h),
        };
        ffi::whiteout_flakes_FlakesFrameStats_delete(h);
        Some(out)
    }
}

/// # Safety
/// As [`frame_stats_from_raw`].
unsafe fn shadow_params_from_raw(h: *mut ffi::whiteout_FlakesShadowParams) -> Option<ShadowParams> {
    if h.is_null() {
        return None;
    }
    unsafe {
        let out = ShadowParams {
            cascade_count: ffi::whiteout_flakes_FlakesShadowParams_get_cascadeCount(h),
            cascade_resolution: ffi::whiteout_flakes_FlakesShadowParams_get_cascadeResolution(h),
            caster_height: ffi::whiteout_flakes_FlakesShadowParams_get_casterHeight(h),
            lambda_split: ffi::whiteout_flakes_FlakesShadowParams_get_lambdaSplit(h),
            depth_bias: ffi::whiteout_flakes_FlakesShadowParams_get_depthBias(h),
            slope_scaled_bias: ffi::whiteout_flakes_FlakesShadowParams_get_slopeScaledBias(h),
            depth_bias_clamp: ffi::whiteout_flakes_FlakesShadowParams_get_depthBiasClamp(h),
            texel_snap: ffi::whiteout_flakes_FlakesShadowParams_get_texelSnap(h) != 0,
            enabled: ffi::whiteout_flakes_FlakesShadowParams_get_enabled(h) != 0,
        };
        ffi::whiteout_flakes_FlakesShadowParams_delete(h);
        Some(out)
    }
}

/// # Safety
/// As [`frame_stats_from_raw`].
unsafe fn assets_stats_from_raw(
    h: *mut ffi::whiteout_FlakesAssetsViewStats,
) -> Option<AssetsViewStats> {
    if h.is_null() {
        return None;
    }
    unsafe {
        let out = AssetsViewStats {
            live_slots: ffi::whiteout_flakes_FlakesAssetsViewStats_get_liveSlots(h),
            loaded_slots: ffi::whiteout_flakes_FlakesAssetsViewStats_get_loadedSlots(h),
            pending_needs: ffi::whiteout_flakes_FlakesAssetsViewStats_get_pendingNeeds(h),
            total_acquires: ffi::whiteout_flakes_FlakesAssetsViewStats_get_totalAcquires(h),
            total_releases: ffi::whiteout_flakes_FlakesAssetsViewStats_get_totalReleases(h),
            total_applies: ffi::whiteout_flakes_FlakesAssetsViewStats_get_totalApplies(h),
            total_apply_misses: ffi::whiteout_flakes_FlakesAssetsViewStats_get_totalApplyMisses(h),
        };
        ffi::whiteout_flakes_FlakesAssetsViewStats_delete(h);
        Some(out)
    }
}

// ── PipelineView ──────────────────────────────────────────────────────────

impl PipelineView {
    /// Create a swap-chain target from a host window handle.
    ///
    /// Returns the new target id, or `0` on failure.
    ///
    /// # Safety
    /// `hwnd` must be a live window handle for the platform's backend: an
    /// `HWND` on Windows, a pre-created `VkSurfaceKHR` elsewhere. It must
    /// stay valid until the target is destroyed. Nothing on this side can
    /// check that, which is why the call is `unsafe`.
    pub unsafe fn create_swap_chain_target(&mut self, hwnd: usize, width: i32, height: i32) -> u32 {
        unsafe {
            whiteout_flakes_FlakesPipelineView_CreateSwapChainTarget(
                self.raw.as_ptr(),
                hwnd,
                width,
                height,
            )
        }
    }

    /// Last-frame stats (geoset / texture / node / particle / segment counts).
    pub fn frame_stats(&self) -> FrameStats {
        // SAFETY: handle is live for the duration of the call; the C side
        // always returns an owned copy for a live view.
        unsafe {
            frame_stats_from_raw(whiteout_flakes_FlakesPipelineView_FrameStats(
                self.raw.as_ptr(),
            ))
            .unwrap_or_default()
        }
    }
}

// ── SceneView ─────────────────────────────────────────────────────────────

impl SceneView {
    /// Set the directory relative model references (textures, child MDX,
    /// PE1 emitters) resolve against.
    ///
    /// This is also the renderer's "about to load into this scene" signal:
    /// it forces the internal disk-backed content provider into existence.
    /// Call it with the model's parent directory *before* [`LoaderView::spawn_unit`],
    /// or the model's relative texture paths will not resolve.
    pub fn set_pe1_base_path(&mut self, path: &str) {
        let cpath = std::ffi::CString::new(path).unwrap_or_default();
        // SAFETY: the C side copies the string into an fs::path and does
        // not retain the pointer.
        unsafe { whiteout_flakes_FlakesSceneView_SetPE1BasePath(self.raw.as_ptr(), cpath.as_ptr()) }
    }
}

// ── ShadowView ────────────────────────────────────────────────────────────

impl ShadowView {
    /// Current cascade-shadow-map tuning.
    pub fn params(&self) -> ShadowParams {
        // SAFETY: as above.
        unsafe {
            shadow_params_from_raw(whiteout_flakes_FlakesShadowView_Params(self.raw.as_ptr()))
                .unwrap_or_default()
        }
    }

    /// Replace the cascade-shadow-map tuning.
    pub fn set_params(&mut self, params: &ShadowParams) {
        // SAFETY: `to_native` hands us an owned handle; the C++ side copies
        // out of it, so we free it as soon as the call returns.
        unsafe {
            let h = params.to_native();
            whiteout_flakes_FlakesShadowView_SetParams(self.raw.as_ptr(), h);
            ffi::whiteout_flakes_FlakesShadowParams_delete(h);
        }
    }
}

// ── AssetsView ────────────────────────────────────────────────────────────

impl AssetsView {
    /// Snapshot diagnostic counters.
    pub fn stats(&self) -> AssetsViewStats {
        // SAFETY: as above.
        unsafe {
            assets_stats_from_raw(whiteout_flakes_FlakesAssetsView_Stats(self.raw.as_ptr()))
                .unwrap_or_default()
        }
    }
}

// ── DncView ───────────────────────────────────────────────────────────────

impl DncView {
    /// Currently-loaded DNC unit-MDL path.
    pub fn unit_mdl_path(&self) -> String {
        // SAFETY: the C side hands back an owned CString; `take_string`
        // consumes and frees it.
        unsafe { take_string(whiteout_flakes_FlakesDncView_UnitMdlPath(self.raw.as_ptr())) }
    }
}

// ── CameraView ────────────────────────────────────────────────────────────

impl CameraView {
    /// World-space look-at point, as `[x, y, z]`.
    pub fn target(&self) -> [f32; 3] {
        let mut out = [0.0f32; 3];
        // SAFETY: the C side writes exactly three floats.
        unsafe {
            whiteout_flakes_FlakesCameraView_GetTargetFlat(self.raw.as_ptr(), out.as_mut_ptr())
        };
        out
    }

    /// Switch to `Direct` mode and set the pose. `roll` is in radians.
    pub fn set_direct_pose(&mut self, pos: [f32; 3], target: [f32; 3], roll: f32) {
        // SAFETY: handle is live for the duration of the call.
        unsafe {
            whiteout_flakes_FlakesCameraView_SetDirectPoseFlat(
                self.raw.as_ptr(),
                pos[0],
                pos[1],
                pos[2],
                target[0],
                target[1],
                target[2],
                roll,
            )
        }
    }
}

// ── ActorView ─────────────────────────────────────────────────────────────

impl ActorView {
    /// World transform, row-major.
    pub fn transform(&self) -> [[f32; 4]; 4] {
        let mut out = [[0.0f32; 4]; 4];
        // SAFETY: `[[f32; 4]; 4]` is 16 contiguous floats, which is exactly
        // what the C side writes.
        unsafe {
            whiteout_flakes_FlakesActorView_TransformFlat(
                self.raw.as_ptr(),
                out.as_mut_ptr().cast::<f32>(),
            )
        };
        out
    }

    /// Set the world transform. `m` is row-major.
    pub fn set_transform(&mut self, m: &[[f32; 4]; 4]) {
        // SAFETY: as above, in the read direction.
        unsafe {
            whiteout_flakes_FlakesActorView_SetTransformFlat(
                self.raw.as_ptr(),
                m.as_ptr().cast::<f32>(),
            )
        }
    }

    /// Animation sequences declared by this actor's source model.
    pub fn sequences(&self) -> Vec<SequenceInfo> {
        // SAFETY: index stays below the reported count; `_at` returns an
        // owned copy that `SequenceInfo` takes over.
        unsafe {
            let n = whiteout_flakes_FlakesActorView_Sequences_count(self.raw.as_ptr());
            (0..n)
                .filter_map(|i| {
                    SequenceInfo::from_raw(whiteout_flakes_FlakesActorView_Sequences_at(
                        self.raw.as_ptr(),
                        i,
                    ))
                })
                .collect()
        }
    }

    /// Camera presets attached to this actor's source model.
    pub fn camera_presets(&self) -> Vec<CameraPreset> {
        // SAFETY: as above.
        unsafe {
            let n = whiteout_flakes_FlakesActorView_CameraPresets_count(self.raw.as_ptr());
            (0..n)
                .filter_map(|i| {
                    CameraPreset::from_raw(whiteout_flakes_FlakesActorView_CameraPresets_at(
                        self.raw.as_ptr(),
                        i,
                    ))
                })
                .collect()
        }
    }
}
