// SPDX-License-Identifier: BSD-3-Clause
// Copyright (c) 2026 Fernando Sahmkow
//
// Hand-written supplement to `flakes.rs`. NOT autogenerated — the
// codegen never touches this file.
//
// Everything here fills a gap the Rust emitter leaves; the "Not yet
// bound" list at the bottom of `flakes.rs` is the authoritative
// inventory of what is still missing. Three categories are covered:
//
//   * Shapes the C generator declines too — `void*` window handles, math
//     types, target readback. These call the hand-written C symbols in
//     `bindings/c/whiteout_flakes_shims.cpp`.
//
//   * Value structs the emitter still declines as a *return* shape.
//     `ShadowView::params` is the last of these; it calls a *generated* C
//     symbol and reads the fields out. `FrameStats`, `AssetsViewStats`,
//     `Sequences` and `CameraPresets` used to be here and are not any
//     more — the emitter grew handle types with getters and borrowed list
//     views, which are better than what this file was doing by hand.
//
//   * Conveniences with no C++ counterpart: backend selection, the
//     bundled shader pack, `Renderer::advance`.
//
// Math crosses as flat arrays rather than through a `Vector3f` type of
// our own: callers already have a math library, and `[f32; 3]` converts
// into every one of them for free.

use crate::flakes::ffi;
use crate::flakes::{ActorView, CameraView, DncView, GfxApi, PipelineView};
use crate::flakes::{SceneView, ShadowParams, ShadowView};
use crate::support::{take_string, Bytes, RawBytes, RawCString};

extern "C" {
    // Generated (whiteout_flakes.cpp), but absent from `flakes.rs`'s own
    // extern block because the emitter skipped the wrapping method.
    fn whiteout_flakes_FlakesShadowView_Params(
        self_: *const ffi::whiteout_FlakesShadowView,
    ) -> *mut ffi::whiteout_FlakesShadowParams;

    // Hand-written (whiteout_flakes_shims.cpp).
    fn whiteout_flakes_BackendCompiledIn(api: i32) -> i32;
    fn whiteout_flakes_FlakesSceneView_SetPE1BasePath(
        self_: *mut ffi::whiteout_FlakesSceneView,
        path: *const core::ffi::c_char,
    );
    fn whiteout_flakes_FlakesSceneView_SetMpqList(
        self_: *mut ffi::whiteout_FlakesSceneView,
        paths: *const *const core::ffi::c_char,
        count: usize,
    );
    fn whiteout_flakes_FlakesSceneView_SetEngineAssetRoot(
        self_: *mut ffi::whiteout_FlakesSceneView,
        root: *const core::ffi::c_char,
    );
    fn whiteout_flakes_FlakesDncView_UnitMdlPath(
        self_: *const ffi::whiteout_FlakesDncView,
    ) -> RawCString;
    fn whiteout_flakes_FlakesPipelineView_CreateSwapChainTarget(
        self_: *mut ffi::whiteout_FlakesPipelineView,
        hwnd: usize,
        width: i32,
        height: i32,
    ) -> u32;
    fn whiteout_flakes_FlakesPipelineView_ReadbackTarget(
        self_: *mut ffi::whiteout_FlakesPipelineView,
        target: u32,
        out_w: *mut i32,
        out_h: *mut i32,
    ) -> RawBytes;
    fn whiteout_flakes_FlakesCameraView_GetTargetFlat(
        self_: *const ffi::whiteout_FlakesCameraView,
        out: *mut f32,
    );
    fn whiteout_flakes_FlakesCameraView_SetDirectPoseFlat(
        self_: *mut ffi::whiteout_FlakesCameraView,
        px: f32,
        py: f32,
        pz: f32,
        tx: f32,
        ty: f32,
        tz: f32,
        roll: f32,
    );
    fn whiteout_flakes_FlakesActorView_TransformFlat(
        self_: *const ffi::whiteout_FlakesActorView,
        out: *mut f32,
    );
    fn whiteout_flakes_FlakesActorView_SetTransformFlat(
        self_: *mut ffi::whiteout_FlakesActorView,
        m: *const f32,
    );
}

// ── Backend selection ─────────────────────────────────────────────────────

/// Whether the linked library was built with this backend at all.
///
/// Distinct from [`Renderer::has_shaders_for`]: a backend can be compiled
/// in with no shader pack bundled, or a pack can be bundled for a backend
/// the library was built without. [`Renderer::preferred_backend`] wants
/// both, which is why it checks both.
pub fn backend_compiled_in(api: GfxApi) -> bool {
    // SAFETY: a pure predicate over compile-time constants; no state.
    unsafe { whiteout_flakes_BackendCompiledIn(api as i32) != 0 }
}

/// Backends to try on this platform, best first.
///
/// Mirrors `RenderSettings::defaultBackend_` — D3D12 on Windows, Metal on
/// macOS, Vulkan everywhere else — then falls through the rest so a build
/// that omits the first choice still finds something.
const fn platform_order() -> &'static [GfxApi] {
    #[cfg(windows)]
    {
        &[GfxApi::D3D12, GfxApi::D3D11, GfxApi::Vulkan, GfxApi::WebGPU]
    }
    #[cfg(target_os = "macos")]
    {
        &[GfxApi::Metal, GfxApi::WebGPU, GfxApi::Vulkan]
    }
    #[cfg(not(any(windows, target_os = "macos")))]
    {
        &[GfxApi::Vulkan, GfxApi::WebGPU]
    }
}

// ── Value-struct round trips ──────────────────────────────────────────────
//
// The C ABI hands back a heap handle; we read the fields out and free it
// immediately, so the value the caller sees owns nothing.

/// # Safety
/// `h` must be a live handle this call takes ownership of.
unsafe fn shadow_params_from_raw(h: *mut ffi::whiteout_FlakesShadowParams) -> Option<ShadowParams> {
    if h.is_null() {
        return None;
    }
    unsafe {
        let out = ShadowParams {
            cascade_count: ffi::whiteout_flakes_FlakesShadowParams_get_cascadeCount(h),
            cascade_resolution: ffi::whiteout_flakes_FlakesShadowParams_get_cascadeResolution(h),
            caster_height: ffi::whiteout_flakes_FlakesShadowParams_get_casterHeight(h),
            lambda_split: ffi::whiteout_flakes_FlakesShadowParams_get_lambdaSplit(h),
            depth_bias: ffi::whiteout_flakes_FlakesShadowParams_get_depthBias(h),
            slope_scaled_bias: ffi::whiteout_flakes_FlakesShadowParams_get_slopeScaledBias(h),
            depth_bias_clamp: ffi::whiteout_flakes_FlakesShadowParams_get_depthBiasClamp(h),
            texel_snap: ffi::whiteout_flakes_FlakesShadowParams_get_texelSnap(h) != 0,
            enabled: ffi::whiteout_flakes_FlakesShadowParams_get_enabled(h) != 0,
        };
        ffi::whiteout_flakes_FlakesShadowParams_delete(h);
        Some(out)
    }
}

// ── PipelineView ──────────────────────────────────────────────────────────

impl PipelineView {
    /// Create a swap-chain target from a host window handle.
    ///
    /// Returns the new target id, or `0` on failure.
    ///
    /// # Safety
    /// `hwnd` must be a live window handle for the platform's backend: an
    /// `HWND` on Windows, a pre-created `VkSurfaceKHR` elsewhere. It must
    /// stay valid until the target is destroyed. Nothing on this side can
    /// check that, which is why the call is `unsafe`.
    pub unsafe fn create_swap_chain_target(&mut self, hwnd: usize, width: i32, height: i32) -> u32 {
        unsafe {
            whiteout_flakes_FlakesPipelineView_CreateSwapChainTarget(
                self.raw.as_ptr(),
                hwnd,
                width,
                height,
            )
        }
    }

    /// Read a target's composited colour back as tightly-packed RGBA8,
    /// row-major from the top-left, with the size it was read at.
    ///
    /// How a GUI shows the renderer somewhere it cannot hand over a window: a
    /// preview thumbnail, a panel the toolkit composites itself, an
    /// off-screen export. Works on every backend this crate exposes — D3D11,
    /// D3D12, Vulkan and WebGPU. Row padding and BGRA ordering are handled
    /// below, so the result is always tight RGBA8 and `len() == w * h * 4`.
    ///
    /// Synchronous: it submits and waits for the copy, so it costs a stall
    /// per call. Right for a panel that updates when something changes, wrong
    /// for a viewport at full rate — give that one a window of its own via
    /// [`create_swap_chain_target`].
    ///
    /// `None` when the target is unknown, was resized out from under the
    /// caller, or is multisampled.
    ///
    /// [`create_swap_chain_target`]: PipelineView::create_swap_chain_target
    pub fn readback_target(&mut self, target: u32) -> Option<(Bytes, i32, i32)> {
        let mut w = 0i32;
        let mut h = 0i32;
        // SAFETY: handle is live for the call; the out-params are real locals,
        // and the returned buffer is owned — `Bytes` takes it over and frees
        // it through the C ABI's own free on drop.
        let bytes = unsafe {
            Bytes::from_raw(whiteout_flakes_FlakesPipelineView_ReadbackTarget(
                self.raw.as_ptr(),
                target,
                &mut w,
                &mut h,
            ))
        }?;
        // A live target that produced no pixels is a failed readback, not an
        // image of size zero — report it the same way as an unknown target.
        if bytes.is_empty() || w <= 0 || h <= 0 {
            return None;
        }
        Some((bytes, w, h))
    }
}

// ── SceneView ─────────────────────────────────────────────────────────────

impl SceneView {
    /// Point this scene's content provider at one or more MPQ archives,
    /// replacing any it already had.
    ///
    /// The MPQ counterpart to [`set_casc_install_path`], and the other half
    /// of browsing with [`StorageBrowser`](crate::StorageBrowser): hand it
    /// the archive you opened and the paths the browser returns become
    /// loadable. Resolved in list order, so a patch archive goes before the
    /// base one.
    ///
    /// Needs the crate's `mpq` feature; without it this is a no-op.
    ///
    /// [`set_casc_install_path`]: SceneView::set_casc_install_path
    pub fn set_mpq_list<S: AsRef<str>>(&mut self, archives: &[S]) {
        // The CStrings must outlive the call, so they are held here rather
        // than built inside the pointer map.
        let owned: Vec<std::ffi::CString> = archives
            .iter()
            .map(|s| std::ffi::CString::new(s.as_ref()).unwrap_or_default())
            .collect();
        let ptrs: Vec<*const core::ffi::c_char> = owned.iter().map(|c| c.as_ptr()).collect();
        // SAFETY: handle is live for the call; `ptrs` points at `owned`,
        // which outlives it, and the C side copies each string.
        unsafe {
            whiteout_flakes_FlakesSceneView_SetMpqList(self.raw.as_ptr(), ptrs.as_ptr(), ptrs.len())
        }
    }

    /// Set the directory relative model references (textures, child MDX,
    /// PE1 emitters) resolve against.
    ///
    /// This is also the renderer's "about to load into this scene" signal:
    /// it forces the internal disk-backed content provider into existence.
    /// Call it with the model's parent directory *before* [`LoaderView::spawn_unit`],
    /// or the model's relative texture paths will not resolve.
    pub fn set_pe1_base_path(&mut self, path: &str) {
        let cpath = std::ffi::CString::new(path).unwrap_or_default();
        // SAFETY: the C side copies the string into an fs::path and does
        // not retain the pointer.
        unsafe { whiteout_flakes_FlakesSceneView_SetPE1BasePath(self.raw.as_ptr(), cpath.as_ptr()) }
    }

    /// Set the root the renderer searches for engine-shipped assets — the
    /// BLS `shaders/` pack.
    ///
    /// **Must be called before [`PipelineView::init_device`]**, or shader
    /// acquisition fails and device init aborts. The C++ default is the
    /// executable's directory, which is never right for a library: your
    /// binary is not shipped beside the renderer's shader pack.
    ///
    /// [`Renderer::use_bundled_shaders`](crate::Renderer::use_bundled_shaders)
    /// points this at the pack `whiteoutflakes-sys` staged at build time,
    /// which is what most callers want.
    pub fn set_engine_asset_root(&mut self, root: &str) {
        let croot = std::ffi::CString::new(root).unwrap_or_default();
        // SAFETY: as above.
        unsafe {
            whiteout_flakes_FlakesSceneView_SetEngineAssetRoot(self.raw.as_ptr(), croot.as_ptr())
        }
    }
}

impl crate::Renderer {
    /// Point the renderer at the shader pack `whiteoutflakes-sys` bundled
    /// at build time, and report whether one was actually there.
    ///
    /// Call before [`PipelineView::init_device`]. Returns `false` when the
    /// crate was built with no shader-pack feature enabled or the build
    /// directory has been cleaned — in that case set your own root with
    /// [`SceneView::set_engine_asset_root`] or device init will fail.
    ///
    /// The bundled path lives under `target/`, so it is valid on the
    /// machine that built the crate and not after you ship the binary. A
    /// distributable application should copy the tree and set the root
    /// itself.
    pub fn use_bundled_shaders(&mut self) -> bool {
        if !whiteoutflakes_sys::has_bundled_shaders() {
            return false;
        }
        let root = whiteoutflakes_sys::ENGINE_ASSET_ROOT;
        match self.scene() {
            Some(mut scene) => {
                scene.set_engine_asset_root(root);
                true
            }
            None => false,
        }
    }

    /// Whether a bundled shader pack covers `api`.
    ///
    /// Enabling the `d3d12` feature and then asking for a D3D11 device is
    /// an easy mistake to make, and without this check the failure it
    /// produces is a shader-read error deep inside
    /// [`PipelineView::init_device`]. Check first and you get to say
    /// something useful instead:
    ///
    /// ```no_run
    /// # use whiteoutflakes::{GfxApi, Renderer};
    /// # let mut r = Renderer::new();
    /// let api = GfxApi::D3D11;
    /// assert!(
    ///     r.has_shaders_for(api),
    ///     "no bundled shaders for {api:?} — enable the matching cargo feature"
    /// );
    /// ```
    /// The best backend this build can actually use here, if any.
    ///
    /// Walks the platform's preference order — D3D12 then D3D11 on
    /// Windows, Metal on macOS, Vulkan elsewhere, mirroring the C++
    /// viewer's own default — and returns the first that is both compiled
    /// into the library and has a bundled shader pack. Prefer this to
    /// naming a backend: which ones exist depends on the platform *and*
    /// on which cargo features the crate was built with.
    ///
    /// `None` means this build has no usable backend here — a macOS build
    /// (the Metal backend isn't vendored), or every backend feature turned
    /// off. Say so rather than calling `init_device` and reading a null
    /// device out of it.
    ///
    /// ```no_run
    /// # use whiteoutflakes::Renderer;
    /// let mut r = Renderer::new();
    /// let api = r.preferred_backend().expect("no usable gfx backend");
    /// r.use_bundled_shaders();
    /// r.pipeline().unwrap().init_device(api);
    /// ```
    pub fn preferred_backend(&self) -> Option<crate::GfxApi> {
        platform_order()
            .iter()
            .copied()
            .find(|&api| backend_compiled_in(api) && self.has_shaders_for(api))
    }

    pub fn has_shaders_for(&self, api: crate::GfxApi) -> bool {
        // The subdirectory each backend reads from. D3D11 is the odd one
        // out — its DXBC sits directly under shaders/ps and shaders/vs.
        let subdir = match api {
            crate::GfxApi::D3D11 => "",
            crate::GfxApi::D3D12 => "d3d12",
            crate::GfxApi::Vulkan => "vulkan",
            crate::GfxApi::WebGPU => "webgpu",
            crate::GfxApi::Metal => "metal",
        };
        whiteoutflakes_sys::has_shaders_for(subdir)
    }

    /// Advance the whole frame by `dt` seconds.
    ///
    /// A frame moves in two halves and they are separate calls on the C++
    /// side: [`SceneView::update`] moves the animation clocks, and
    /// [`Renderer::tick`](crate::Renderer::tick) moves the particle, PE1,
    /// ribbon and corn effects simulations. A host that calls only `tick` gets
    /// effects over a model frozen on frame zero, which looks like a broken
    /// model rather than a missing call. This does both, in that order.
    ///
    /// Honours the transport: with playback paused or stopped the scene
    /// ignores `dt`, so this is still the call to make every frame.
    ///
    /// Drives the default scene only. A host running several scenes calls
    /// `update` and `tick` per scene itself.
    pub fn advance(&mut self, dt: f32) {
        if let Some(mut scene) = self.scene() {
            scene.update(dt);
        }
        self.tick(dt);
    }
}

impl SceneView {
    /// Point this scene at the shader pack `whiteoutflakes-sys` bundled at
    /// build time.
    ///
    /// The [`Renderer::use_bundled_shaders`](crate::Renderer::use_bundled_shaders)
    /// convenience covers the single-scene case; this is the equivalent
    /// for a host driving several scenes.
    pub fn use_bundled_shaders(&mut self) -> bool {
        if !whiteoutflakes_sys::has_bundled_shaders() {
            return false;
        }
        self.set_engine_asset_root(whiteoutflakes_sys::ENGINE_ASSET_ROOT);
        true
    }
}

// ── ShadowView ────────────────────────────────────────────────────────────

impl ShadowView {
    /// Current cascade-shadow-map tuning.
    pub fn params(&self) -> ShadowParams {
        // SAFETY: as above.
        unsafe {
            shadow_params_from_raw(whiteout_flakes_FlakesShadowView_Params(self.raw.as_ptr()))
                .unwrap_or_default()
        }
    }
}

// ── DncView ───────────────────────────────────────────────────────────────

impl DncView {
    /// Currently-loaded DNC unit-MDL path.
    pub fn unit_mdl_path(&self) -> String {
        // SAFETY: the C side hands back an owned CString; `take_string`
        // consumes and frees it.
        unsafe { take_string(whiteout_flakes_FlakesDncView_UnitMdlPath(self.raw.as_ptr())) }
    }
}

// ── CameraView ────────────────────────────────────────────────────────────

impl CameraView {
    /// World-space look-at point, as `[x, y, z]`.
    pub fn target(&self) -> [f32; 3] {
        let mut out = [0.0f32; 3];
        // SAFETY: the C side writes exactly three floats.
        unsafe {
            whiteout_flakes_FlakesCameraView_GetTargetFlat(self.raw.as_ptr(), out.as_mut_ptr())
        };
        out
    }

    /// Switch to `Direct` mode and set the pose. `roll` is in radians.
    pub fn set_direct_pose(&mut self, pos: [f32; 3], target: [f32; 3], roll: f32) {
        // SAFETY: handle is live for the duration of the call.
        unsafe {
            whiteout_flakes_FlakesCameraView_SetDirectPoseFlat(
                self.raw.as_ptr(),
                pos[0],
                pos[1],
                pos[2],
                target[0],
                target[1],
                target[2],
                roll,
            )
        }
    }
}

// ── ActorView ─────────────────────────────────────────────────────────────

impl ActorView {
    /// World transform, row-major.
    pub fn transform(&self) -> [[f32; 4]; 4] {
        let mut out = [[0.0f32; 4]; 4];
        // SAFETY: `[[f32; 4]; 4]` is 16 contiguous floats, which is exactly
        // what the C side writes.
        unsafe {
            whiteout_flakes_FlakesActorView_TransformFlat(
                self.raw.as_ptr(),
                out.as_mut_ptr().cast::<f32>(),
            )
        };
        out
    }

    /// Set the world transform. `m` is row-major.
    pub fn set_transform(&mut self, m: &[[f32; 4]; 4]) {
        // SAFETY: as above, in the read direction.
        unsafe {
            whiteout_flakes_FlakesActorView_SetTransformFlat(
                self.raw.as_ptr(),
                m.as_ptr().cast::<f32>(),
            )
        }
    }
}
