// SPDX-License-Identifier: BSD-3-Clause
// Copyright (c) 2026 Fernando Sahmkow
//
// Hand-written supplement to the generated C ABI. NOT autogenerated —
// `python -m tools.bindings.codegen flakes` never touches this file.
//
// Three shapes the generator declines, and why each is here rather than
// expressed as an annotation:
//
//   1. `void*` window handles. `PipelineView::CreateSwapChainTarget` takes
//      an HWND / VkSurfaceKHR, which the generator rejects because it
//      can't tell an opaque OS handle from an unbound class pointer. The
//      shim retypes it as a uintptr_t so every binding language can pass
//      one without a pointer type of its own.
//
//   2. Math types in signatures. `Vector3f` / `Matrix44f` reach the C ABI
//      as opaque handles owned by WhiteoutLib's common TU, which would
//      make every pose call allocate. Flat float arrays cross the
//      boundary as-is and map onto the binding's own math types.
//
//   3. `std::vector<T>` returns of bound structs. The generator lowers
//      `vector<string>` to a (count, at) pair but has no equivalent for
//      vectors of class types; these follow the same pattern by hand.
//
// Plus one outright generator bug: it moves string returns into the
// CString wrapper, which a `const std::string&` return can't satisfy.
// `DncView::UnitMdlPath` is `@bind skip`ped and re-declared here under
// the symbol the generator would otherwise have produced.

#include "whiteout_flakes.h"

#include <whiteout/flakes/actor_view.h>
#include <whiteout/flakes/display.h>
#include <whiteout/flakes/renderer.h>
#include <whiteout/flakes/util/path_utf8.h>
#include <whiteout/flakes/views.h>

#include <cstdint>
#include <filesystem>
#include <string>

namespace {
using namespace whiteout::flakes;

// The generated TUs use the same reinterpret_cast idiom; the opaque C
// handle is the C++ object's address, so the cast is an identity.
template <typename T, typename H>
T* as(H* h) {
    return reinterpret_cast<T*>(h);
}
template <typename T, typename H>
const T* as(const H* h) {
    return reinterpret_cast<const T*>(h);
}
} // namespace

extern "C" {

// ── PipelineView: swap-chain bring-up ─────────────────────────────────────

/* Create a swap-chain target from a host window handle. `hwnd` is an HWND
 * on Windows and a pre-created VkSurfaceKHR elsewhere, in both cases
 * carried as an integer so no binding needs a pointer type for it. */
uint32_t whiteout_flakes_FlakesPipelineView_CreateSwapChainTarget(
    whiteout_FlakesPipelineView* self, uintptr_t hwnd, int32_t width, int32_t height) {
    return as<PipelineView>(self)->CreateSwapChainTarget(
        reinterpret_cast<void*>(hwnd), width, height);
}

// ── SceneView: filesystem path ────────────────────────────────────────────

/* Set the directory relative model references resolve against. Also the
 * host's "about to load into this scene" signal — it forces the internal
 * file content provider into existence, so call it before SpawnUnit. */
void whiteout_flakes_FlakesSceneView_SetPE1BasePath(whiteout_FlakesSceneView* self,
                                                    const char* path) {
    as<SceneView>(self)->SetPE1BasePath(FsPathFromUtf8(path ? path : ""));
}

/* Root for the engine-shipped BLS shader pack. Must be set before
 * InitDevice by any host that isn't an executable sitting next to
 * `shaders/` — which is every language binding. */
void whiteout_flakes_FlakesSceneView_SetEngineAssetRoot(whiteout_FlakesSceneView* self,
                                                        const char* root) {
    as<SceneView>(self)->SetEngineAssetRoot(FsPathFromUtf8(root ? root : ""));
}

// ── DncView: string return ────────────────────────────────────────────────

/* Currently-loaded DNC unit-MDL path. Free with whiteout_CString_free. */
whiteout_CString whiteout_flakes_FlakesDncView_UnitMdlPath(const whiteout_FlakesDncView* self) {
    auto* owned = new std::string(as<DncView>(self)->UnitMdlPath());
    return {owned->c_str(), owned->size(), owned};
}

// ── CameraView: pose ──────────────────────────────────────────────────────

/* Look-at point, written as {x, y, z} into `out`. */
void whiteout_flakes_FlakesCameraView_GetTargetFlat(const whiteout_FlakesCameraView* self,
                                                    float* out) {
    const Vector3f t = as<CameraView>(self)->GetTarget();
    out[0] = t.x;
    out[1] = t.y;
    out[2] = t.z;
}

/* Switch to Direct mode and set the pose. */
void whiteout_flakes_FlakesCameraView_SetDirectPoseFlat(whiteout_FlakesCameraView* self,
                                                        float px, float py, float pz,
                                                        float tx, float ty, float tz,
                                                        float roll) {
    as<CameraView>(self)->SetDirectPose(Vector3f{px, py, pz}, Vector3f{tx, ty, tz}, roll);
}

// ── ActorView: transform ──────────────────────────────────────────────────

/* World transform, written row-major into `out[16]` — the same order
 * `Matrix44f::data` stores it in, so this is a straight copy. */
void whiteout_flakes_FlakesActorView_TransformFlat(const whiteout_FlakesActorView* self,
                                                   float* out) {
    const Matrix44f m = as<ActorView>(self)->Transform();
    for (int r = 0; r < 4; ++r)
        for (int c = 0; c < 4; ++c)
            out[r * 4 + c] = m.data[r][c];
}

/* Counterpart of TransformFlat; `m` is 16 row-major floats. */
void whiteout_flakes_FlakesActorView_SetTransformFlat(whiteout_FlakesActorView* self,
                                                      const float* m) {
    Matrix44f out{};
    for (int r = 0; r < 4; ++r)
        for (int c = 0; c < 4; ++c)
            out.data[r][c] = m[r * 4 + c];
    as<ActorView>(self)->SetTransform(out);
}

// ── ActorView: vector-of-struct returns ───────────────────────────────────
//
// Both accessors rebuild the vector per call, so a full walk is O(n²).
// The lists are short (sequences and camera presets are per-model, tens
// at most) and the alternative — handing out a snapshot handle — buys a
// lifetime problem for a saving nobody would notice.

size_t whiteout_flakes_FlakesActorView_Sequences_count(const whiteout_FlakesActorView* self) {
    return as<ActorView>(self)->Sequences().size();
}

/* Copy of the sequence at `index`, or NULL when out of range. Free with
 * whiteout_flakes_FlakesSequenceInfo_delete. */
whiteout_FlakesSequenceInfo* whiteout_flakes_FlakesActorView_Sequences_at(
    const whiteout_FlakesActorView* self, size_t index) {
    const auto seqs = as<ActorView>(self)->Sequences();
    if (index >= seqs.size())
        return nullptr;
    return reinterpret_cast<whiteout_FlakesSequenceInfo*>(new SequenceInfo(seqs[index]));
}

size_t whiteout_flakes_FlakesActorView_CameraPresets_count(const whiteout_FlakesActorView* self) {
    return as<ActorView>(self)->CameraPresets().size();
}

/* Copy of the preset at `index`, or NULL when out of range. Free with
 * whiteout_flakes_FlakesCameraPreset_delete. */
whiteout_FlakesCameraPreset* whiteout_flakes_FlakesActorView_CameraPresets_at(
    const whiteout_FlakesActorView* self, size_t index) {
    const auto presets = as<ActorView>(self)->CameraPresets();
    if (index >= presets.size())
        return nullptr;
    return reinterpret_cast<whiteout_FlakesCameraPreset*>(new CameraPreset(presets[index]));
}

} // extern "C"
