"""Emit the Wc3Shaders permutation labels as a C++ table for bls_permuter_test.

The test checks that `bls::SelectPermutes` lands on the permutation whose
feature set is the one the render state asks for. The meaning of each index is
the shader repo's, not ours: every label here comes from the `map_*` function
that compiles that permutation (externals/Wc3Shaders/compile_all_slang.py), so
a wrong bit position in the permuter shows up as a label mismatch instead of
agreeing with itself.

    python tools/gen_wc3_perm_labels.py

Re-run after a Wc3Shaders bump that touches a mapper, and commit the output.
"""

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SHADERS = ROOT / "externals" / "Wc3Shaders"
OUT = ROOT / "tests" / "generated" / "wc3_perm_labels.inc"

FAMILIES = [
    "hd_vs",
    "hd_ps",
    "crystal_ps",
    "sd_on_hd_ps",
    "sd_highspec_vs",
    "sd_classic_ps",
    "popcorn_vs",
    "popcorn_ps",
]


def main() -> int:
    sys.path.insert(0, str(SHADERS))
    import compile_all_slang as cas  # noqa: E402  (path set just above)

    lines = [
        "// Generated by tools/gen_wc3_perm_labels.py from",
        "// externals/Wc3Shaders/compile_all_slang.py. Do not edit.",
        "#pragma once",
        "",
        "namespace wc3_perm_labels {",
        "",
    ]
    for fam in FAMILIES:
        count = cas.FAMILY_CONFIGS[fam].perm_count
        mapper = cas.MAPPERS[fam]
        lines.append(f"inline constexpr unsigned k_{fam}_count = {count};")
        lines.append(f"inline constexpr const char* k_{fam}[{count}] = {{")
        for i in range(count):
            lines.append(f"    {json.dumps(mapper(i).label)},")
        lines.append("};")
        lines.append("")
    lines.append("} // namespace wc3_perm_labels")
    lines.append("")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
